import {describe, expect, it} from "vitest";
import {toInquiry, toInquiryRecord} from "@/features/inquiries/infrastructure/mappers/inquiry-record-mapper";
import {InquiryMappingError} from "@/features/inquiries/infrastructure/errors/inquiry-mapping-error";
import {parseSubmissionPayload} from "@/features/inquiries/infrastructure/validation/submission-payload";
import {InquiryTestBuilder} from "@/features/inquiries/testing/builders/inquiry-test-builder";

describe("Inquiry record mapping", () => {
  it("round trips every field, timestamps, consent, and status", () => { const inquiry = new InquiryTestBuilder().buildReconstituted({status: "quoted", updatedAt: new Date("2026-01-03")}); const record = toInquiryRecord(inquiry); const restored = toInquiry(record); expect(toInquiryRecord(restored)).toEqual(record); expect(record.privacyAcceptedAt).toBe("2026-01-01T00:00:00.000Z"); });
  it("rejects invalid persisted state with an explicit mapping error", () => { const record = toInquiryRecord(new InquiryTestBuilder().buildNew()); expect(() => toInquiry({...record, sourcePath: "https://evil.test"})).toThrow(InquiryMappingError); });
  it("isolates record collections from the aggregate", () => { const inquiry = new InquiryTestBuilder().buildNew(); const record = toInquiryRecord(inquiry); expect(Object.isFrozen(record.items)).toBe(true); expect(Object.isFrozen(record.items[0])).toBe(true); expect(toInquiry(record).items).not.toBe(record.items); });
  it("preserves normalized multiline messages", () => { const inquiry = new InquiryTestBuilder().with({message: "Line one\r\nخط دوم"}).buildNew(); const restored = toInquiry(toInquiryRecord(inquiry)); expect(restored.message).toBe("Line one\nخط دوم"); });
});
const validPayload = () => ({contact: {fullName: "Test Customer", email: "customer@example.test", phone: "+1 202 555 0100", preferredMethod: "email"}, location: {country: "United States"}, privacy: {accepted: true, policyVersion: "test-policy-v1"}, source: {locale: "en", path: "/en/products"}, items: [{productId: "test-product-1", quantity: 12, unit: "pieces"}]});
describe("external payload boundary", () => {
  it("reconstructs fresh one-item and multi-item inputs without a consent timestamp", () => { const original = validPayload(); const one = parseSubmissionPayload(original); expect(one.status).toBe("success"); if (one.status !== "success") return; expect(one.value).not.toBe(original); expect(one.value.contact).not.toBe(original.contact); expect(one.value.items[0]).not.toBe(original.items[0]); expect(one.value.privacy).not.toHaveProperty("acceptedAt"); original.contact.fullName = "Changed"; original.items[0].quantity = 99; expect(one.value.contact.fullName).toBe("Test Customer"); expect(one.value.items[0].quantity).toBe(12); const multi = validPayload(); multi.items.push({productId: "test-product-2", quantity: 2, unit: "pieces"}); expect(parseSubmissionPayload(multi)).toMatchObject({status: "success", value: {items: [{productId: "test-product-1"}, {productId: "test-product-2"}]}}); });
  it.each([null, [], "payload", 42, Object.assign(Object.create({polluted: true}), validPayload())])("rejects unsafe roots", (value) => expect(parseSubmissionPayload(value).status).toBe("failure"));
  it.each([{items: []}, {...validPayload(), contact: null}, {...validPayload(), contact: []}, {...validPayload(), location: "US"}, {...validPayload(), privacy: null}, {...validPayload(), source: "en"}, {...validPayload(), items: [null]}, {...validPayload(), items: [[]]}, {...validPayload(), items: [{productId: 1, quantity: 1, unit: "pieces"}]}, {...validPayload(), items: [{productId: "test", quantity: "1", unit: "pieces"}]}, {...validPayload(), items: [{productId: "test", quantity: Number.NaN, unit: "pieces"}]}, {...validPayload(), items: [{productId: "test", quantity: Number.POSITIVE_INFINITY, unit: "pieces"}]}, {...validPayload(), items: [{productId: "test", quantity: 1, unit: "boxes"}]}, {...validPayload(), source: {locale: "de", path: "/de"}}, {...validPayload(), privacy: {accepted: "yes", policyVersion: "test"}}, {...validPayload(), destination: null}, {...validPayload(), message: 42}, {...validPayload(), unexpected: true}, {...validPayload(), contact: {...validPayload().contact, unexpected: true}}])("returns safe failure for malformed payload", (value) => { const result = parseSubmissionPayload(value); expect(result.status).toBe("failure"); expect(JSON.stringify(result)).not.toContain("customer@example.test"); });
});
