import {describe,expect,it,vi} from "vitest";
import type {SubmitInquiryInput} from "@/features/inquiries/application/dto/inquiry-dto";
import {createInquiryRequestHandler,inquiryRequestSizeLimit} from "@/features/inquiries/infrastructure/http/inquiry-request-handler";
const valid:SubmitInquiryInput={contact:{fullName:"Customer Name",email:"customer@example.test",phone:"+12025550100",preferredMethods:["email"]},location:{country:"TR"},privacy:{accepted:true,policyVersion:"inquiry-contact-consent-v2"},source:{locale:"en",path:"/en/inquiry"},items:[{productId:"ylp-gb-250-og-rd",palletCount:12}]};
const request=(body:string,headers:HeadersInit={})=>new Request("https://yolpol.com/api/inquiries",{method:"POST",body,headers:{"Content-Type":"application/json",Origin:"https://yolpol.com",...headers}});
describe("Inquiry request handler",()=>{
  it("returns minimal persisted success",async()=>{const execute=vi.fn().mockResolvedValue({status:"accepted",inquiry:{inquiryId:"real-id",status:"received",createdAt:"2026-08-24T00:00:00.000Z"}});const response=await createInquiryRequestHandler(()=>({execute}))(request(JSON.stringify(valid)));expect(response.status).toBe(201);expect(await response.json()).toEqual({status:"created",inquiryId:"real-id"});expect(execute).toHaveBeenCalledWith(valid);});
  it.each([[request("{"),400,"invalid_request"],[new Request("https://yolpol.com/api/inquiries",{method:"POST",body:"{}",headers:{"Content-Type":"text/plain"}}),415,"unsupported_media_type"],[request("x".repeat(inquiryRequestSizeLimit+1)),413,"payload_too_large"],[request(JSON.stringify(valid),{Origin:"https://attacker.example"}),403,"invalid_origin"],[request(JSON.stringify({...valid,items:[]})),422,"validation_failed"]])("rejects unsafe requests",async(input,status,code)=>{const response=await createInquiryRequestHandler(()=>({execute:vi.fn().mockResolvedValue({status:"validation_failed",field:"request"})}))(input);expect(response.status).toBe(status);expect(await response.json()).toMatchObject({code});});
  it("does not leak persistence details",async()=>{const response=await createInquiryRequestHandler(()=>({execute:vi.fn().mockResolvedValue({status:"persistence_failed",detail:"sql secret"})}))(request(JSON.stringify(valid)));expect(response.status).toBe(503);expect(await response.text()).not.toContain("secret");});
});
