import {describe, expect, it, vi} from "vitest";
import {createAiProviderRegistryAuditHandler, createGetAiProviderRegistryHandler, createMutateAiProviderRegistryHandler} from "@/features/ai-provider-registry/infrastructure/http/ai-provider-registry-request-handlers";

const principal = {staffAccountId: "account-1", teamMemberId: "member-1", role: "SUPER_ADMIN" as const, displayName: "Admin", actorReference: "staff:member-1"};
const credential = "synthetic-session-credential";
const request = (method = "GET", body?: unknown, origin = "https://yolpol.com") => new Request("http://localhost/api/staff/ai-providers", {method, headers: {Cookie: `yolpol_staff_session=${credential}`, ...(origin ? {Origin: origin} : {}), ...(body === undefined ? {} : {"Content-Type": "application/json"})}, body: body === undefined ? undefined : JSON.stringify(body)});
const validProvider = {operation: "SAVE_PROVIDER", expectedVersion: 0, id: "provider-a", adapterKey: "groq", displayName: "Provider A", enabled: true, priority: 10};
function fixtures() { const access = {resolveSession: {execute: vi.fn().mockResolvedValue({status: "authenticated", principal})}}; const registry = {getRegistry: {execute: vi.fn().mockResolvedValue({status: "found", registry: {providers: [], profiles: [], credentialReferences: []}})}, readAuditHistory: {execute: vi.fn().mockResolvedValue({status: "found", events: []})}, saveProvider: {execute: vi.fn().mockResolvedValue({status: "saved", provider: {id: "provider-a"}})}, saveProfile: {execute: vi.fn()}, saveCredentialReference: {execute: vi.fn()}}; const rateLimiter = {consume: vi.fn().mockReturnValue({allowed: true})}; return {access, registry, rateLimiter, options: {rateLimiter, environment: {NODE_ENV: "development"}, approvedDevelopmentOrigins: new Set(["http://localhost"])}}; }

describe("AI provider registry HTTP boundary", () => {
  it("requires authenticated reads and rejects query strings", async () => { const value = fixtures(); const handler = createGetAiProviderRegistryHandler(() => value.access, () => value.registry, value.options); expect((await handler(new Request("http://localhost/api/staff/ai-providers"))).status).toBe(401); expect((await handler(new Request("http://localhost/api/staff/ai-providers?actor=forged", {headers: {Cookie: `yolpol_staff_session=${credential}`}}))).status).toBe(400); });
  it("requires exact Origin, bounded JSON, exact command shapes, and rejects actor spoofing", async () => { const value = fixtures(); const handler = createMutateAiProviderRegistryHandler(() => value.access, () => value.registry, value.options); expect((await handler(request("POST", validProvider, ""))).status).toBe(403); expect((await handler(request("POST", {...validProvider, actorReference: "staff:attacker"}))).status).toBe(400); const large = request("POST", validProvider); large.headers.set("Content-Length", String(33 * 1024)); expect((await handler(large)).status).toBe(413); expect(value.registry.saveProvider.execute).not.toHaveBeenCalled(); });
  it("passes only exact fields plus the session principal and maps optimistic conflicts", async () => { const value = fixtures(); const handler = createMutateAiProviderRegistryHandler(() => value.access, () => value.registry, value.options); expect((await handler(request("POST", validProvider))).status).toBe(200); expect(value.registry.saveProvider.execute).toHaveBeenCalledWith({...validProvider, principal}); value.registry.saveProvider.execute.mockResolvedValueOnce({status: "conflict"}); expect((await handler(request("POST", validProvider))).status).toBe(409); });
  it("maps credential capability denial, rate limits mutations, and protects audit", async () => { const value = fixtures(); value.registry.saveCredentialReference.execute.mockResolvedValueOnce({status: "forbidden"}); const mutate = createMutateAiProviderRegistryHandler(() => value.access, () => value.registry, value.options); const credentialBody = {operation: "SAVE_CREDENTIAL_REFERENCE", expectedVersion: 0, id: "credential-a", providerId: "provider-a", alias: "Primary", credentialReference: "groq-primary", enabled: true, priority: 10}; expect((await mutate(request("POST", credentialBody))).status).toBe(403); value.rateLimiter.consume.mockReturnValueOnce({allowed: false, retryAfterSeconds: 9}); expect((await mutate(request("POST", validProvider))).status).toBe(429); const audit = createAiProviderRegistryAuditHandler(() => value.access, () => value.registry, value.options); expect((await audit(request())).status).toBe(200); expect(value.registry.readAuditHistory.execute).toHaveBeenCalledWith(principal); });
  it("returns safe service errors without dependency detail", async () => { const value = fixtures(); value.access.resolveSession.execute.mockRejectedValueOnce(new Error("database internals")); const handler = createGetAiProviderRegistryHandler(() => value.access, () => value.registry, value.options); const response = await handler(request()); expect(response.status).toBe(503); expect(await response.text()).not.toContain("database internals"); });
});
