import {resolve} from "node:path";
import {drizzle} from "drizzle-orm/node-postgres";
import {migrate} from "drizzle-orm/node-postgres/migrator";
import {Pool} from "pg";
import {afterAll, afterEach, beforeAll, beforeEach, describe, expect, it} from "vitest";

import type {AiProviderRegistryEntity, AiProviderRegistryEvent} from "@/features/ai-provider-registry/application/ports/ai-provider-registry-ports";
import {GetEligibleAiModelProfiles} from "@/features/ai-provider-registry/application/use-cases/get-eligible-ai-model-profiles";
import {AiCredentialReference} from "@/features/ai-provider-registry/domain/entities/ai-credential-reference";
import {AiModelProfile} from "@/features/ai-provider-registry/domain/entities/ai-model-profile";
import {AiProviderConfiguration} from "@/features/ai-provider-registry/domain/entities/ai-provider-configuration";
import {PostgresAiProviderRegistryRepository} from "@/features/ai-provider-registry/infrastructure/persistence/postgres/repositories/postgres-ai-provider-registry-repository";
import {aiProviderRegistryPostgresSchema} from "@/features/ai-provider-registry/infrastructure/persistence/postgres/schema/ai-provider-registry-schema";
import {safeIntegrationPoolConfig} from "@/features/inquiries/testing/integration/postgres-test-database";

let pool: Pool; let repository: PostgresAiProviderRegistryRepository;
const instant = (minute: number) => new Date(`2026-09-01T00:${String(minute).padStart(2, "0")}:00.000Z`);
const provider = (id: string, version = 1, enabled = true, priority = 10, minute = version - 1) => AiProviderConfiguration.create({id, adapterKey: "groq", displayName: `Provider ${id}`, enabled, priority, version, createdAt: instant(0), updatedAt: instant(minute), updatedBy: "staff:member-1"});
const profile = (id: string, providerId: string, priority = 10) => AiModelProfile.create({id, providerId, name: `Profile ${id}`, modelIdentifier: `model/${id}`, enabled: true, priority, capabilities: ["TEXT_GENERATION", "TRANSLATION"], generationSettings: {temperature: 0.2, topP: null, maxOutputTokens: 2048}, version: 1, createdAt: instant(0), updatedAt: instant(0), updatedBy: "staff:member-1"});
const credential = (id: string, providerId: string, priority = 10) => AiCredentialReference.create({id, providerId, alias: `Alias ${id}`, credentialReference: `${providerId}-${id}`, enabled: true, priority, version: 1, createdAt: instant(0), updatedAt: instant(0), updatedBy: "staff:member-1"});
function event(id: string, type: AiProviderRegistryEvent["entityType"], next: AiProviderRegistryEntity, previous: AiProviderRegistryEntity | null): AiProviderRegistryEvent { return {id, entityType: type, entityId: next.id, changeType: previous ? previous.enabled === next.enabled ? "UPDATED" : next.enabled ? "ENABLED" : "DISABLED" : "CREATED", previousEntity: previous, newEntity: next, actorReference: next.updatedBy, occurredAt: next.updatedAt}; }
async function clean() { await pool.query("truncate table ai_provider_runtime_health, ai_model_profile_capabilities, ai_credential_references, ai_model_profiles, ai_provider_registry_events, ai_provider_configs"); }

beforeAll(async () => { pool = new Pool(safeIntegrationPoolConfig(process.env.INTEGRATION_DATABASE_URL)); await migrate(drizzle(pool, {schema: aiProviderRegistryPostgresSchema}), {migrationsFolder: resolve("drizzle")}); repository = new PostgresAiProviderRegistryRepository(pool); });
beforeEach(async () => { const identity = await pool.query<{current_database: string; current_user: string}>("select current_database(), current_user"); expect(identity.rows[0]).toEqual({current_database: "yolpol_integration", current_user: "yolpol_test"}); await clean(); });
afterEach(clean); afterAll(async () => { if (pool) await pool.end(); });

describe("PostgresAiProviderRegistryRepository", () => {
  it("round-trips providers, profiles, capabilities, credentials, safe audit snapshots, and deterministic ordering", async () => { const providerB = provider("provider-b", 1, true, 10); const providerA = provider("provider-a", 1, true, 10); await repository.saveProvider(providerB, event("aipre_provider-b", "PROVIDER", providerB, null), 0); await repository.saveProvider(providerA, event("aipre_provider-a", "PROVIDER", providerA, null), 0); const model = profile("profile-a", providerA.id); await repository.saveProfile(model, event("aipre_profile-a", "MODEL_PROFILE", model, null), 0); const reference = credential("credential-a", providerA.id); await repository.saveCredentialReference(reference, event("aipre_credential-a", "CREDENTIAL_REFERENCE", reference, null), 0); const registry = await repository.read(); expect(registry.providers.map((item) => item.id)).toEqual(["provider-a", "provider-b"]); expect(registry.profiles[0]).toMatchObject({capabilities: ["TEXT_GENERATION", "TRANSLATION"], generationSettings: {temperature: 0.2, topP: null, maxOutputTokens: 2048}}); expect(registry.credentialReferences[0]?.credentialReference).toBe("provider-a-credential-a"); const history = await repository.readEvents(100); expect(history).toHaveLength(4); expect(JSON.stringify(history)).not.toContain("authorization"); });
  it("enforces foreign keys and duplicate names/aliases", async () => { const orphan = profile("orphan-profile", "missing"); expect(await repository.saveProfile(orphan, event("aipre_orphan", "MODEL_PROFILE", orphan, null), 0)).toBe("missing_parent"); const value = provider("provider-a"); await repository.saveProvider(value, event("aipre_provider", "PROVIDER", value, null), 0); const first = credential("credential-a", value.id); const second = AiCredentialReference.create({...credential("credential-b", value.id), alias: first.alias}); await repository.saveCredentialReference(first, event("aipre_first", "CREDENTIAL_REFERENCE", first, null), 0); expect(await repository.saveCredentialReference(second, event("aipre_second", "CREDENTIAL_REFERENCE", second, null), 0)).toBe("duplicate"); });
  it("persists multiple ordered credential references and keeps eligibility through one disabled reference", async () => {
    const value = provider("groq-provider"); await repository.saveProvider(value, event("aipre_multi-provider", "PROVIDER", value, null), 0);
    const model = profile("groq-profile", value.id); await repository.saveProfile(model, event("aipre_multi-profile", "MODEL_PROFILE", model, null), 0);
    const primary = AiCredentialReference.create({...credential("credential-primary", value.id, 10), alias: "Primary", credentialReference: "secret://ai/groq/primary"});
    const backup = AiCredentialReference.create({...credential("credential-backup", value.id, 10), alias: "Backup", credentialReference: "secret://ai/groq/backup"});
    await repository.saveCredentialReference(primary, event("aipre_multi-primary", "CREDENTIAL_REFERENCE", primary, null), 0); await repository.saveCredentialReference(backup, event("aipre_multi-backup", "CREDENTIAL_REFERENCE", backup, null), 0);
    expect((await repository.read()).credentialReferences.map(({id, alias}) => [id, alias])).toEqual([["credential-backup", "Backup"], ["credential-primary", "Primary"]]);
    const disabledBackup = AiCredentialReference.create({...backup, enabled: false, version: 2, updatedAt: instant(1)});
    expect(await repository.saveCredentialReference(disabledBackup, event("aipre_multi-disable", "CREDENTIAL_REFERENCE", disabledBackup, backup), 1)).toBe("saved");
    const registry = await repository.read(); expect(registry.credentialReferences.map(({id, enabled}) => [id, enabled])).toEqual([["credential-backup", false], ["credential-primary", true]]); expect(registry.credentialReferences.map(({credentialReference}) => credentialReference)).toEqual(["secret://ai/groq/backup", "secret://ai/groq/primary"]);
    const eligible = await new GetEligibleAiModelProfiles(repository).execute("TEXT_GENERATION"); expect(eligible).toHaveLength(1); expect(eligible[0]!.credentialReferences.map(({id}) => id)).toEqual(["credential-primary"]);
  });
  it("allows one compare-and-swap update and atomically rolls back on audit failure", async () => { const first = provider("provider-a"); await repository.saveProvider(first, event("aipre_initial", "PROVIDER", first, null), 0); const left = provider("provider-a", 2, false, 1, 1); const right = provider("provider-a", 2, true, 2, 2); expect((await Promise.all([repository.saveProvider(left, event("aipre_left", "PROVIDER", left, first), 1), repository.saveProvider(right, event("aipre_right", "PROVIDER", right, first), 1)])).sort()).toEqual(["conflict", "saved"]); const persisted = await repository.findProvider("provider-a"); const next = provider("provider-a", 3, false, 3, 3); await expect(repository.saveProvider(next, event("aipre_initial", "PROVIDER", next, persisted), 2)).rejects.toBeDefined(); expect((await repository.findProvider("provider-a"))?.version).toBe(2); });
  it("rejects a stale Model Profile update without overwriting state or appending an event", async () => {
    const parent = provider("provider-a"); await repository.saveProvider(parent, event("aipre_profile-parent", "PROVIDER", parent, null), 0); const first = profile("profile-a", parent.id); await repository.saveProfile(first, event("aipre_profile-create", "MODEL_PROFILE", first, null), 0);
    const current = AiModelProfile.create({...first, name: "Current profile", version: 2, updatedAt: instant(1)}); expect(await repository.saveProfile(current, event("aipre_profile-current", "MODEL_PROFILE", current, first), 1)).toBe("saved"); const eventCount = (await repository.readEvents(100)).length;
    const stale = AiModelProfile.create({...first, name: "Stale profile", version: 2, updatedAt: instant(2)}); expect(await repository.saveProfile(stale, event("aipre_profile-stale", "MODEL_PROFILE", stale, first), 1)).toBe("conflict");
    expect(await repository.findProfile(first.id)).toMatchObject({name: "Current profile", version: 2}); expect(await repository.readEvents(100)).toHaveLength(eventCount);
  });
  it("rejects a stale Credential Reference update without overwriting state or appending an event", async () => {
    const parent = provider("provider-a"); await repository.saveProvider(parent, event("aipre_credential-parent", "PROVIDER", parent, null), 0); const first = credential("credential-a", parent.id); await repository.saveCredentialReference(first, event("aipre_credential-create", "CREDENTIAL_REFERENCE", first, null), 0);
    const current = AiCredentialReference.create({...first, alias: "Current credential", version: 2, updatedAt: instant(1)}); expect(await repository.saveCredentialReference(current, event("aipre_credential-current", "CREDENTIAL_REFERENCE", current, first), 1)).toBe("saved"); const eventCount = (await repository.readEvents(100)).length;
    const stale = AiCredentialReference.create({...first, alias: "Stale credential", version: 2, updatedAt: instant(2)}); expect(await repository.saveCredentialReference(stale, event("aipre_credential-stale", "CREDENTIAL_REFERENCE", stale, first), 1)).toBe("conflict");
    expect(await repository.findCredentialReference(first.id)).toMatchObject({alias: "Current credential", version: 2}); expect(await repository.readEvents(100)).toHaveLength(eventCount);
  });
  it("database-enforces immutable audit events", async () => { const value = provider("provider-a"); await repository.saveProvider(value, event("aipre_immutable", "PROVIDER", value, null), 0); await expect(pool.query("update ai_provider_registry_events set entity_id = 'changed' where id = 'aipre_immutable'")).rejects.toMatchObject({code: "55000"}); await expect(pool.query("delete from ai_provider_registry_events where id = 'aipre_immutable'")).rejects.toMatchObject({code: "55000"}); });
});
