import {readFileSync} from "node:fs";
import {renderToStaticMarkup} from "react-dom/server";
import {describe, expect, it, vi} from "vitest";
vi.mock("@/i18n/navigation", () => ({useRouter: () => ({refresh: vi.fn()})}));
import {AiProviderRegistryPanel, type AiProviderRegistryPanelLabels} from "@/features/ai-provider-registry/presentation/components/ai-provider-registry-panel";
import {getLocaleDirection} from "@/i18n/locale";

const labels: AiProviderRegistryPanelLabels = {eyebrow: "Registry", title: "AI Provider Registry", description: "No provider calls", providers: "Providers", profiles: "Profiles", credentials: "Credential references", audit: "Audit", empty: "Empty", readOnly: "Read only", id: "ID", adapterKey: "Adapter", displayName: "Display name", name: "Name", modelIdentifier: "Model ID", provider: "Provider", alias: "Alias", secretReference: "Safe secret reference", secretReferenceHelp: "Reference only. Never paste an API key.", enabled: "Enabled", priority: "Priority", capabilities: "Capabilities", temperature: "Temperature", topP: "Top P", maxOutputTokens: "Max output", version: "Version", updatedAt: "Updated", updatedBy: "Updated by", createProvider: "Create provider", createProfile: "Create profile", createCredential: "Add reference", save: "Save", saving: "Saving", saved: "Saved", edit: "Edit", statuses: {enabled: "Enabled", disabled: "Disabled"}, errors: {conflict: "Conflict", invalid: "Invalid", forbidden: "Forbidden", rate_limited: "Limited", failed: "Failed"}, eventTypes: {CREATED: "Created", UPDATED: "Updated", ENABLED: "Enabled", DISABLED: "Disabled"}, entityTypes: {PROVIDER: "Provider", MODEL_PROFILE: "Profile", CREDENTIAL_REFERENCE: "Credential"}, capabilityLabels: {TEXT_GENERATION: "Text", TRANSLATION: "Translation", STRUCTURED_OUTPUT: "Structured", TOOL_CALLING: "Tools"}};
const registry = {providers: [{id: "provider-a", adapterKey: "groq", displayName: "Provider A", enabled: true, priority: 1, version: 1, createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", updatedBy: "staff:member-1"}], profiles: [], credentialReferences: [{id: "credential-a", providerId: "provider-a", alias: "Primary", credentialReference: "groq-primary", enabled: true, priority: 1, version: 1, createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", updatedBy: "staff:member-1"}]};
describe("AiProviderRegistryPanel", () => {
  it("renders safe read-only summaries without mutation controls", () => { const html = renderToStaticMarkup(<AiProviderRegistryPanel locale="fa" registry={registry} events={[]} mayManageProviders={false} mayManageCredentialReferences={false} labels={labels} />); expect(html).toContain("Provider A"); expect(html).toContain("groq-primary"); expect(html).toContain("Read only"); expect(html).not.toContain('type="password"'); expect(html).not.toContain('type="submit"'); });
  it("allows Admin provider/profile editing while keeping credential editing Super-Admin-only", () => { const admin = renderToStaticMarkup(<AiProviderRegistryPanel locale="en" registry={registry} events={[]} mayManageProviders mayManageCredentialReferences={false} labels={labels} />); expect(admin).toContain("Create provider"); expect(admin).not.toContain("Add reference"); const superAdmin = renderToStaticMarkup(<AiProviderRegistryPanel locale="en" registry={registry} events={[]} mayManageProviders mayManageCredentialReferences labels={labels} />); expect(superAdmin).toContain("Add reference"); expect(superAdmin).toContain("Reference only"); expect(superAdmin).not.toContain('type="password"'); });
  it("gives every editable Provider form a unique matching adapter-key datalist", () => { const secondProvider = {...registry.providers[0]!, id: "provider-b", displayName: "Provider B"}; const html = renderToStaticMarkup(<AiProviderRegistryPanel locale="en" registry={{...registry, providers: [...registry.providers, secondProvider]}} events={[]} mayManageProviders mayManageCredentialReferences={false} labels={labels} />); const datalistIds = [...html.matchAll(/<datalist id="([^"]+)"/gu)].map((match) => match[1]!); const listReferences = [...html.matchAll(/<input[^>]+list="([^"]+)"[^>]*>/gu)].map((match) => match[1]!); expect(datalistIds).toHaveLength(3); expect(new Set(datalistIds).size).toBe(datalistIds.length); expect(listReferences.sort()).toEqual([...datalistIds].sort()); });
  it("keeps message parity and direction across four locales", () => { const namespaces = ["en", "tr", "fa", "ar"].map((locale) => JSON.parse(readFileSync(`src/i18n/messages/${locale}.json`, "utf8")).AiProviderRegistry as Record<string, unknown>); const keys = (value: unknown, prefix = ""): string[] => typeof value === "object" && value !== null && !Array.isArray(value) ? Object.entries(value as Record<string, unknown>).flatMap(([key, child]) => keys(child, prefix ? `${prefix}.${key}` : key)) : [prefix]; expect(namespaces.map((item) => keys(item).sort())).toEqual(Array(4).fill(keys(namespaces[0]).sort())); expect(["en", "tr", "fa", "ar"].map((locale) => getLocaleDirection(locale as "en" | "tr" | "fa" | "ar"))).toEqual(["ltr", "ltr", "rtl", "rtl"]); });
});
