import {describe,expect,it} from "vitest";
import {InquiryValidationError,InquiryTransitionError} from "@/features/inquiries/domain/errors/inquiry-errors";
import {InquiryTestBuilder} from "@/features/inquiries/testing/builders/inquiry-test-builder";
import {inquiryFixture} from "@/features/inquiries/testing/fixtures/inquiry-fixtures";
import {contactMethods,targetCountries} from "@/features/inquiries/domain/types/inquiry-types";
import {normalizeInquiryCustomerDetails,normalizeInternationalPhone,normalizePreferredContactMethods,normalizeTelegramUsername} from "@/features/inquiries/domain/validation/inquiry-input-validation";
import {InquiryId} from "@/features/inquiries/domain/value-objects/inquiry-id";

describe("Inquiry aggregate",()=>{
  it("normalizes contact channels and creates a NEW inquiry",()=>{const inquiry=new InquiryTestBuilder().buildNew();expect(inquiry.status).toBe("NEW");expect(inquiry.contact).toMatchObject({email:"CUSTOMER@example.test",phone:"+442079460958",telegramUsername:"@test_customer",preferredMethods:["email","telegram"]});});
  it.each([{contact:{...inquiryFixture.contact,phone:"123"}},{contact:{...inquiryFixture.contact,preferredMethods:[]}},{contact:{...inquiryFixture.contact,preferredMethods:["whatsapp"] as const,whatsappPhone:undefined}},{contact:{...inquiryFixture.contact,preferredMethods:["telegram"] as const,telegramUsername:undefined}},{location:{country:"US"}},{destination:{city:"Dubai"}},{privacy:{...inquiryFixture.privacy,accepted:false}},{items:[]},{items:[{...inquiryFixture.items[0],quantity:0}]},{items:[{...inquiryFixture.items[0],quantity:1_000_000_001}]}])("rejects invalid creation input",change=>expect(()=>new InquiryTestBuilder().with(change).buildNew()).toThrow(InquiryValidationError));
  it("accepts all channels and multiple rows totaling more than 26 pallets",()=>{const inquiry=new InquiryTestBuilder().with({contact:{...inquiryFixture.contact,preferredMethods:["email","whatsapp","telegram"],whatsappPhone:"+971501234567"},items:[{...inquiryFixture.items[0],quantity:26},{...inquiryFixture.items[0],productId:"test-product-2",sku:"TEST-2",slug:"second",quantity:26}]}).buildNew();expect(inquiry.items.map(({quantity})=>quantity)).toEqual([26,26]);});
  it("accepts packages for a new Inquiry but keeps historical-only units out of new creation",()=>{expect(new InquiryTestBuilder().with({items:[{...inquiryFixture.items[0],quantity:37,unit:"packages"}]}).buildNew().items[0]).toMatchObject({quantity:37,unit:"packages"});expect(()=>new InquiryTestBuilder().with({items:[{...inquiryFixture.items[0],unit:"pieces"}]}).buildNew()).toThrow(InquiryValidationError);expect(()=>new InquiryTestBuilder().with({items:[{...inquiryFixture.items[0],unit:"truckloads"}]}).buildNew()).toThrow(InquiryValidationError);});
  it("preserves legacy persisted country and unit values",()=>{const inquiry=new InquiryTestBuilder().with({location:{country:"United Kingdom"},items:[{...inquiryFixture.items[0],quantity:100,unit:"pieces"}]}).buildReconstituted();expect(inquiry.location.country).toBe("United Kingdom");expect(inquiry.items[0].unit).toBe("pieces");});
  it("enforces lifecycle transitions",()=>{const inquiry=new InquiryTestBuilder().buildNew();inquiry.transitionTo("WAITING_FOR_TEAM",new Date("2026-01-02"));expect(inquiry.status).toBe("WAITING_FOR_TEAM");expect(()=>inquiry.transitionTo("NEW",new Date("2026-01-03"))).toThrow(InquiryTransitionError);});
  it.each([["989121234567","+989121234567"],["+989121234567","+989121234567"],["98 912 123 4567","+989121234567"],["+98 912 123 4567","+989121234567"],["905321234567","+905321234567"],["+90 (532) 123 45 67","+905321234567"],["9647701234567","+9647701234567"],["971501234567","+971501234567"]] as const)("normalizes international phone %s",(value,expected)=>expect(normalizeInternationalPhone(value,"contact.phone")).toBe(expected));
  it.each([""," ","123456","0123456789","00989121234567","++989121234567","98+91234567","98 912A34567","1234567890123456","-1234567","+(1234567)","1--234567","12- -34567","1.5","1e10","Infinity","۱۲۳۴۵۶۷","١٢٣٤٥٦٧","123\n4567","123\u00004567"])("rejects invalid international phone %j",value=>expect(()=>normalizeInternationalPhone(value,"contact.phone")).toThrow(InquiryValidationError));
  it("normalizes main and WhatsApp phones independently with exactly one plus",()=>expect(normalizeInquiryCustomerDetails({...inquiryFixture,contact:{...inquiryFixture.contact,phone:"989121234567",whatsappPhone:"905321234567",telegramUsername:undefined,preferredMethods:["email","whatsapp"]}}).contact).toMatchObject({phone:"+989121234567",whatsappPhone:"+905321234567"}));
  it.each([["buyer_name","@buyer_name"],["@buyer_name","@buyer_name"],["abcde","@abcde"],[`a${"b".repeat(31)}`,`@a${"b".repeat(31)}`],["A123_","@A123_"]] as const)("canonicalizes Telegram username %s",(value,expected)=>expect(normalizeTelegramUsername(value)).toBe(expected));
  it.each(["","@","abcd","@abcd","1abcd","_abcd","ab cd","@@abcde","@abc@de","https://t.me/name","t.me/name","نامکاربری","abc-dé","abc.def","abc-def","abc+def","abc/def","abc\ndef","abc\u0000def",`a${"b".repeat(32)}`])("rejects malformed Telegram username %j",value=>expect(()=>normalizeTelegramUsername(value)).toThrow(InquiryValidationError));
  it.each([
    ["email"],["whatsapp"],["telegram"],["email","whatsapp"],["email","telegram"],["whatsapp","telegram"],["email","whatsapp","telegram"],
  ] as const)("accepts and canonically orders methods %j",(...methods)=>expect(normalizePreferredContactMethods([...methods].reverse())).toEqual(contactMethods.filter(method=>(methods as readonly string[]).includes(method))));
  it.each([[],["email","email"],["phone"],["sms"],[1],[null],"email",null,undefined])("rejects invalid preferred methods %j",value=>expect(()=>normalizePreferredContactMethods(value)).toThrow(InquiryValidationError));
  it.each(targetCountries)("accepts approved customer country %s",country=>expect(normalizeInquiryCustomerDetails({...inquiryFixture,location:{country}}).location.country).toBe(country));
  it("defines exactly 14 approved countries with Iran first",()=>expect(targetCountries).toEqual(["IR","TR","IQ","AM","AZ","TM","AF","PK","AE","SA","QA","KW","BH","OM"]));
  it.each([["IR","IR"],["IR","TR"],["TR","IR"]] as const)("accepts customer and destination countries %s to %s",(country,destinationCountry)=>expect(normalizeInquiryCustomerDetails({...inquiryFixture,location:{country},destination:{country:destinationCountry}})).toMatchObject({location:{country},destination:{country:destinationCountry}}));
  it.each(["US","GB","tr","ae","XX",""," Türkiye ",42,null,undefined])("rejects unknown customer country %j",country=>expect(()=>normalizeInquiryCustomerDetails({...inquiryFixture,location:{country}})).toThrow(InquiryValidationError));
  it.each(["a","A_1-z","x".repeat(128)])("accepts Inquiry ID %s",id=>expect(InquiryId.create(id).value).toBe(id));
  it.each(["","a/b","with space","x".repeat(129),"bad\u0000id"," leading","trailing "])("rejects Inquiry ID %j",id=>expect(()=>InquiryId.create(id)).toThrow(InquiryValidationError));
  it.each(["pieces","packages","pallets","truckloads"] as const)("reconstitutes historical %s units",unit=>expect(new InquiryTestBuilder().with({items:[{...inquiryFixture.items[0],unit}]}).buildReconstituted().items[0].unit).toBe(unit));
  it.each(["email","whatsapp","telegram","phone"] as const)("reconstitutes historical %s preference",method=>{const contact={...inquiryFixture.contact,preferredMethods:[method],whatsappPhone:method==="whatsapp"?"legacy phone":undefined,telegramUsername:method==="telegram"?"legacy.name":undefined};expect(new InquiryTestBuilder().with({contact}).buildReconstituted().contact.preferredMethods).toEqual([method]);});
});
