import {describe, expect, it} from "vitest";
import {Inquiry} from "@/features/inquiries/domain/entities/inquiry";
import {InquiryTransitionError, InquiryValidationError} from "@/features/inquiries/domain/errors/inquiry-errors";
import {inquiryStatuses, type InquiryStatus} from "@/features/inquiries/domain/types/inquiry-types";
import {InquiryId} from "@/features/inquiries/domain/value-objects/inquiry-id";
import {InquiryTestBuilder} from "@/features/inquiries/testing/builders/inquiry-test-builder";
import {inquiryFixture} from "@/features/inquiries/testing/fixtures/inquiry-fixtures";

describe("Inquiry values and aggregate", () => {
  it.each(["a", "A_1-z", "x".repeat(128)])("accepts URL-safe ID %s", (id) => expect(InquiryId.create(id).value).toBe(id));
  it.each(["", "a/b", "x".repeat(129), "with space"])("rejects invalid ID %s", (id) => expect(() => InquiryId.create(id)).toThrow(InquiryValidationError));
  it("creates received with normalized contact and equal isolated dates", () => { const inquiry = new InquiryTestBuilder().buildNew(); expect(inquiry.status).toBe("received"); expect(inquiry.contact.email).toBe("customer@example.test"); expect(inquiry.createdAt).toEqual(inquiry.updatedAt); expect(Object.isFrozen(inquiry.id)).toBe(true); });
  it.each([{contact: {...inquiryFixture.contact, fullName: "x"}}, {contact: {...inquiryFixture.contact, company: "x"}}, {contact: {...inquiryFixture.contact, email: "invalid"}}, {contact: {...inquiryFixture.contact, phone: "123"}}, {contact: {...inquiryFixture.contact, preferredMethod: "telegram" as const, telegramUsername: undefined}}, {location: {country: "x"}}, {destination: {city: "Paris"}}, {message: "x".repeat(2001)}, {privacy: {...inquiryFixture.privacy, accepted: false}}, {source: {...inquiryFixture.source, path: "https://evil.test"}}, {source: {...inquiryFixture.source, path: "javascript:alert(1)"}}, {items: []}, {items: [{...inquiryFixture.items[0], quantity: 0}]}, {items: [{...inquiryFixture.items[0], quantity: 1.5}]}, {items: [{...inquiryFixture.items[0], quantity: 1_000_000_001}]}, {items: [{...inquiryFixture.items[0]}, {...inquiryFixture.items[0]}]}])("rejects invalid primitive input", (change) => expect(() => new InquiryTestBuilder().with(change).buildNew()).toThrow(InquiryValidationError));
  it("supports international phones, Telegram normalization, Unicode messages, destinations, and multiple items", () => { const inquiry = new InquiryTestBuilder().with({contact: {...inquiryFixture.contact, preferredMethod: "telegram", telegramUsername: "@valid_name"}, items: [...inquiryFixture.items, {...inquiryFixture.items[0], productId: "test-product-2", sku: "TEST-2", slug: "other", productName: "محصول", unit: "pallets"}], message: "پیام مشتری"}).buildNew(); expect(inquiry.contact.telegramUsername).toBe("valid_name"); expect(inquiry.items).toHaveLength(2); expect(inquiry.message).toBe("پیام مشتری"); });
  it.each(["/en", "/en/", "/en/products", "/fa/products/example-slug"])("accepts locale-correlated path %s", (path) => { const locale = path.slice(1, 3) as "en" | "fa"; expect(new InquiryTestBuilder().with({source: {locale, path}}).buildNew().source.path).toBe(path); });
  it.each(["/contact", "/fa/products", "/en/../contact", "/en/./products", "/en//products", "//evil.example", "https://evil.example", "http://evil.example", "javascript:alert(1)", "data:text/html,test", "/en\\products", "/en/%2fproducts", "/en/%2e%2e/contact", "/en/%zz", "/en\r\nproducts", "/en?query=1", "/en#fragment", " /en", ""])("rejects unsafe or locale-inconsistent source path %s", (path) => expect(() => new InquiryTestBuilder().with({source: {locale: "en", path}}).buildNew()).toThrow(InquiryValidationError));
  it.each(["fullName", "company"] as const)("rejects controls in contact %s", (field) => expect(() => new InquiryTestBuilder().with({contact: {...inquiryFixture.contact, [field]: "Bad\nValue"}}).buildNew()).toThrow(InquiryValidationError));
  it.each(["Bad\u0000Value", "Bad\u007fValue", "Bad\u0085Value", "Bad\u2028Value"])("rejects unsafe single-line controls", (productName) => expect(() => new InquiryTestBuilder().with({items: [{...inquiryFixture.items[0], productName}]}).buildNew()).toThrow(InquiryValidationError));
  it("normalizes multiline message newlines and rejects unsafe message controls", () => { expect(new InquiryTestBuilder().with({message: "Satır 1\r\nپیام ۲"}).buildNew().message).toBe("Satır 1\nپیام ۲"); expect(() => new InquiryTestBuilder().with({message: "unsafe\u0000message"}).buildNew()).toThrow(InquiryValidationError); });
  it.each(inquiryStatuses)("reconstitutes %s", (status) => expect(new InquiryTestBuilder().buildReconstituted({status}).status).toBe(status));
  it("rejects invalid persisted timestamps and consent evidence", () => { expect(() => new InquiryTestBuilder().with({createdAt: new Date("invalid")}).buildReconstituted()).toThrow(); expect(() => Inquiry.reconstitute({...inquiryFixture, status: "received", updatedAt: new Date("2025-01-01"), privacy: {...inquiryFixture.privacy, accepted: true}})).toThrow(); expect(() => Inquiry.reconstitute({...inquiryFixture, status: "received", updatedAt: inquiryFixture.createdAt, privacy: {...inquiryFixture.privacy, accepted: false}})).toThrow(); });
  it("preserves historical consent time and rejects malformed persisted consent time", () => { const historical = new Date("2025-12-31T23:00:00.000Z"); const inquiry = new InquiryTestBuilder().with({privacy: {...inquiryFixture.privacy, acceptedAt: historical}}).buildReconstituted(); expect(inquiry.privacy.acceptedAt).toEqual(historical); expect(() => new InquiryTestBuilder().with({privacy: {...inquiryFixture.privacy, acceptedAt: new Date("invalid")}}).buildReconstituted()).toThrow(InquiryValidationError); });
  it("defensively isolates nested values, arrays, and dates", () => { const mutable = {...inquiryFixture.items[0]}; const date = new Date(inquiryFixture.createdAt); const inquiry = new InquiryTestBuilder().with({items: [mutable], createdAt: date, privacy: {...inquiryFixture.privacy, acceptedAt: date}}).buildNew(); mutable.productName = "changed"; date.setFullYear(2030); const exposed = inquiry.createdAt; exposed.setFullYear(2040); expect(inquiry.items[0].productName).toBe("Test Bottle"); expect(inquiry.createdAt.getUTCFullYear()).toBe(2026); expect(Object.isFrozen(inquiry.items)).toBe(true); expect(Object.isFrozen(inquiry.items[0])).toBe(true); });
});

describe("Inquiry lifecycle", () => {
  const allowed: readonly [InquiryStatus, InquiryStatus][] = [["received", "processing"], ["received", "spam"], ["processing", "contacted"], ["processing", "spam"], ["contacted", "quoted"], ["contacted", "lost"], ["contacted", "spam"], ["quoted", "won"], ["quoted", "lost"], ["quoted", "spam"]];
  it.each(allowed)("allows %s -> %s", (from, to) => { const inquiry = new InquiryTestBuilder().buildReconstituted({status: from}); inquiry.transitionTo(to, new Date("2026-01-02")); expect(inquiry.status).toBe(to); });
  it("rejects arbitrary backward/terminal transitions", () => { for (const [from, to] of [["processing", "received"], ["won", "processing"], ["spam", "received"]] as const) expect(() => new InquiryTestBuilder().buildReconstituted({status: from}).transitionTo(to, new Date("2026-01-02"))).toThrow(InquiryTransitionError); });
  it("rejects backdated transitions but preserves timestamp for same-status no-op", () => { const inquiry = new InquiryTestBuilder().buildReconstituted({status: "processing", updatedAt: new Date("2026-01-02")}); inquiry.transitionTo("processing", new Date("2020-01-01")); expect(inquiry.updatedAt).toEqual(new Date("2026-01-02")); expect(() => inquiry.transitionTo("contacted", new Date("2026-01-01"))).toThrow(InquiryTransitionError); });
});
