import {describe,expect,it} from "vitest";
import {createInitialInquiryFormState,inquiryAddedProductFocusId,inquiryFailureFocusId,inquiryFormReducer,type InquiryFormAction} from "@/features/inquiries/presentation/state/inquiry-form-reducer";
describe("Inquiry form reducer",()=>{
  it("toggles methods canonically while retaining conditional drafts",()=>{let state=createInitialInquiryFormState(true);state=inquiryFormReducer(state,{type:"update_field",field:"whatsappPhone",value:"+905551234567"});state=inquiryFormReducer(state,{type:"toggle_contact_method",method:"telegram",selected:true});state=inquiryFormReducer(state,{type:"toggle_contact_method",method:"email",selected:true});state=inquiryFormReducer(state,{type:"toggle_contact_method",method:"telegram",selected:false});expect(state.fields.preferredMethods).toEqual(["email"]);expect(state.fields.whatsappPhone).toBe("+905551234567");});
  it("adds and edits a fresh pallet line",()=>{let state=createInitialInquiryFormState(true);state=inquiryFormReducer(state,{type:"select_pending_product",productId:"product-1"});state=inquiryFormReducer(state,{type:"add_product",availableIds:["product-1"]});expect(state.lines).toEqual([{productId:"product-1",quantityText:"",unit:"pallets"}]);state=inquiryFormReducer(state,{type:"change_quantity",index:0,value:"12"});expect(state.lines[0].quantityText).toBe("12");expect(inquiryAddedProductFocusId(0)).toBe("inquiry-quantity-0");});
  it("retains an available package unit and falls back to pallets when a product changes",()=>{let state=createInitialInquiryFormState(true);state=inquiryFormReducer(state,{type:"select_pending_product",productId:"product-1"});state=inquiryFormReducer(state,{type:"add_product",availableIds:["product-1"]});state=inquiryFormReducer(state,{type:"change_unit",index:0,unit:"packages"});state=inquiryFormReducer(state,{type:"change_product",index:0,productId:"product-2",availableUnits:["pallets","packages"]});expect(state.lines[0]).toMatchObject({productId:"product-2",unit:"packages"});state=inquiryFormReducer(state,{type:"change_product",index:0,productId:"product-3",availableUnits:["pallets"]});expect(state.lines[0]).toMatchObject({productId:"product-3",unit:"pallets"});});
  it.each([
    {type:"update_field",field:"fullName",value:"Buyer"},{type:"update_field",field:"company",value:"Company"},{type:"update_field",field:"email",value:"buyer@example.test"},{type:"update_field",field:"phone",value:"+905551234567"},{type:"update_field",field:"whatsappPhone",value:"+905551234568"},{type:"update_field",field:"telegramUsername",value:"@buyer_name"},{type:"update_field",field:"country",value:"TR"},{type:"update_field",field:"city",value:"Istanbul"},{type:"update_field",field:"destinationCountry",value:"AE"},{type:"update_field",field:"destinationCity",value:"Dubai"},{type:"update_field",field:"message",value:"Message"},{type:"update_consent",value:true},{type:"select_pending_product",productId:"product-2"},{type:"toggle_contact_method",method:"email",selected:true},
  ] as InquiryFormAction[])("clears stale feedback for $type",action=>{const succeeded=inquiryFormReducer(createInitialInquiryFormState(true),{type:"submission_succeeded",inquiryId:"reference"});const result=inquiryFormReducer(succeeded,action);expect(result.feedback).toBe("idle");expect(result.inquiryId).toBeNull();expect(result.failure).toBeNull();});
  it("blocks duplicate and unavailable additions",()=>{let state=createInitialInquiryFormState(true);state=inquiryFormReducer(state,{type:"select_pending_product",productId:"product-1"});state=inquiryFormReducer(state,{type:"add_product",availableIds:["product-1"]});state=inquiryFormReducer(state,{type:"select_pending_product",productId:"product-1"});expect(inquiryFormReducer(state,{type:"add_product",availableIds:["product-1"]}).lines).toHaveLength(1);state=inquiryFormReducer(state,{type:"select_pending_product",productId:"unknown"});expect(inquiryFormReducer(state,{type:"add_product",availableIds:["product-2"]}).lines).toHaveLength(1);});
  it("supports nine products and remove/re-add resets the quantity draft",()=>{const ids=Array.from({length:9},(_,index)=>`product-${index+1}`);let state=createInitialInquiryFormState(true);for(const id of ids){state=inquiryFormReducer(state,{type:"select_pending_product",productId:id});state=inquiryFormReducer(state,{type:"add_product",availableIds:ids});}expect(state.lines).toHaveLength(9);state=inquiryFormReducer(state,{type:"change_quantity",index:0,value:"9"});state=inquiryFormReducer(state,{type:"remove_product",productId:ids[0]});state=inquiryFormReducer(state,{type:"select_pending_product",productId:ids[0]});state=inquiryFormReducer(state,{type:"add_product",availableIds:ids});expect(state.lines).toHaveLength(9);expect(state.lines.at(-1)).toEqual({productId:ids[0],quantityText:"",unit:"pallets"});});
  it.each([["fullName",undefined,"inquiry-fullName"],["email",undefined,"inquiry-email"],["phone",undefined,"inquiry-phone"],["preferredContact",undefined,"inquiry-preferredContact"],["whatsappPhone",undefined,"inquiry-whatsappPhone"],["telegramUsername",undefined,"inquiry-telegramUsername"],["products",undefined,"inquiry-products"],["quantity",2,"inquiry-quantity-2"],["quantityUnit",2,"inquiry-quantityUnit-2"],["privacy",undefined,"inquiry-privacy"]] as const)("maps %s focus target",(field,itemIndex,expected)=>expect(inquiryFailureFocusId({field,code:"required",itemIndex})).toBe(expected));
});
