import {describe, expect, it} from "vitest";

import {createInitialInquiryFormState, inquiryAddedProductFocusId, inquiryFailureFocusId, inquiryFormReducer, type InquiryFormAction, type InquiryFormState} from "@/features/inquiries/presentation/state/inquiry-form-reducer";

const first = {productId: "ylp-gb-250-og-rd", quantityText: "12", unit: "pallets" as const};
const second = {productId: "ylp-gb-250-cl-rd", quantityText: "7", unit: "packages" as const};
const prepared = (): InquiryFormState => inquiryFormReducer(inquiryFormReducer(createInitialInquiryFormState(true), {type: "apply_preselection", lines: [first, second]}), {type: "prepared"});

describe("Inquiry form reducer", () => {
  it.each([
    {type:"update_field",field:"fullName",value:"Buyer"},{type:"update_field",field:"company",value:"Company"},{type:"update_field",field:"email",value:"buyer@example.test"},{type:"update_field",field:"phone",value:"+1 202 555 0100"},{type:"update_field",field:"preferredMethod",value:"phone"},{type:"update_field",field:"country",value:"Türkiye"},{type:"update_field",field:"city",value:"Istanbul"},{type:"update_field",field:"destinationCountry",value:"France"},{type:"update_field",field:"destinationCity",value:"Paris"},{type:"update_field",field:"message",value:"Message"},{type:"update_consent",value:true},{type:"select_pending_product",productId:"ylp-gb-500-cl-rd"},{type:"remove_product",productId:first.productId},{type:"change_quantity",index:0,value:"13"},{type:"change_unit",index:0,value:"pieces"},{type:"apply_preselection",lines:[first]},{type:"reset"},
  ] as InquiryFormAction[])("clears prepared feedback for $type", (action) => { const result=inquiryFormReducer(prepared(),action); expect(result.feedback).toBe("idle"); expect(result.failure).toBeNull(); });

  it("clears prepared feedback when a Product is added", () => { let state=prepared(); state=inquiryFormReducer(state,{type:"select_pending_product",productId:"ylp-gb-500-cl-rd"}); state=inquiryFormReducer(inquiryFormReducer(state,{type:"prepared"}),{type:"add_product",availableIds:["ylp-gb-500-cl-rd"]}); expect(state.feedback).toBe("idle"); expect(state.lines[2]).toEqual({productId:"ylp-gb-500-cl-rd",quantityText:"",unit:""}); });
  it("preserves other rows and restores a neutral empty state after final removal", () => { let state=inquiryFormReducer(prepared(),{type:"remove_product",productId:first.productId}); expect(state.lines).toEqual([second]); expect(state.lines[0].quantityText).toBe("7"); state=inquiryFormReducer(state,{type:"remove_product",productId:second.productId}); expect(state.lines).toEqual([]); expect(state.feedback).toBe("idle"); expect(state.failure).toBeNull(); });
  it("clears a Product-required failure after adding a Product", () => { let state=inquiryFormReducer(createInitialInquiryFormState(true),{type:"validation_failed",failure:{field:"products",code:"required"}}); state=inquiryFormReducer(state,{type:"select_pending_product",productId:first.productId}); state=inquiryFormReducer(state,{type:"add_product",availableIds:[first.productId]}); expect(state.failure).toBeNull(); expect(state.lines).toEqual([{productId:first.productId,quantityText:"",unit:""}]); });
  it("blocks duplicate and unavailable additions", () => { let state=inquiryFormReducer(createInitialInquiryFormState(true),{type:"apply_preselection",lines:[first]}); state=inquiryFormReducer(state,{type:"select_pending_product",productId:first.productId}); expect(inquiryFormReducer(state,{type:"add_product",availableIds:[first.productId]}).lines).toEqual([first]); state=inquiryFormReducer(state,{type:"select_pending_product",productId:"unknown"}); expect(inquiryFormReducer(state,{type:"add_product",availableIds:[second.productId]}).lines).toEqual([first]); });
  it("supports all nine Products without a tenth duplicate and restores availability after removal", () => { const ids=Array.from({length:9},(_,index)=>`product-${index+1}`); let state=createInitialInquiryFormState(true); for(const id of ids){state=inquiryFormReducer(state,{type:"select_pending_product",productId:id});state=inquiryFormReducer(state,{type:"add_product",availableIds:ids.filter((candidate)=>!state.lines.some(({productId})=>productId===candidate))});} expect(state.lines).toHaveLength(9); const full=state; state=inquiryFormReducer(state,{type:"select_pending_product",productId:ids[0]}); expect(inquiryFormReducer(state,{type:"add_product",availableIds:[]}).lines).toEqual(full.lines); state=inquiryFormReducer(state,{type:"remove_product",productId:ids[0]}); expect(state.lines).toHaveLength(8); expect(state.lines.some(({productId})=>productId===ids[0])).toBe(false); });
  it("changes one row without mutating another", () => { const state=inquiryFormReducer(prepared(),{type:"change_quantity",index:1,value:"99"}); expect(state.lines[0]).toEqual(first); expect(state.lines[1]).toEqual({...second,quantityText:"99"}); });
  it("maps validation and addition focus targets to stable controls", () => { expect(inquiryFailureFocusId({field:"fullName",code:"invalid"})).toBe("inquiry-fullName"); expect(inquiryFailureFocusId({field:"email",code:"invalid"})).toBe("inquiry-email"); expect(inquiryFailureFocusId({field:"phone",code:"invalid"})).toBe("inquiry-phone"); expect(inquiryFailureFocusId({field:"products",code:"required"})).toBe("inquiry-products"); expect(inquiryFailureFocusId({field:"quantity",code:"required",itemIndex:2,productId:"product-3"})).toBe("inquiry-quantity-2"); expect(inquiryFailureFocusId({field:"unit",code:"required",itemIndex:1,productId:"product-2"})).toBe("inquiry-unit-1"); expect(inquiryFailureFocusId({field:"privacy",code:"required"})).toBe("inquiry-privacy"); expect(inquiryAddedProductFocusId(3)).toBe("inquiry-quantity-3"); });
});
