import {describe, expect, it, vi} from "vitest";
import {CalculateExportLoadPlan} from "@/features/export-logistics/application/use-cases/calculate-export-load-plan";
import {ListEligibleLogisticsProducts} from "@/features/export-logistics/application/use-cases/list-eligible-logistics-products";

const packaging = {unitsPerPackage: 10, packagesPerPallet: 10, unitsPerPallet: 100, palletGrossWeightKg: 100};
const product = {id: "p1", sku: "SKU-1", name: "Bottle", status: "published", locale: "en", packaging};

describe("Export Logistics catalog trust boundary", () => {
  it.each([null, {}, {lines: []}, {lines: [null]}, {lines: [{productId: " ", palletCount: 1}]}, {lines: [{productId: "p1", palletCount: "1"}]}, {lines: [{productId: "p1", palletCount: Number.NaN}]}])("rejects invalid input before catalog access", async (request) => {
    const findById = vi.fn().mockRejectedValue(new Error("must not run"));
    const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById}).execute(request, "en");
    expect(result.status).toBe("invalid_plan");
    expect(findById).not.toHaveBeenCalled();
  });
  it("rejects duplicates before catalog access", async () => { const findById = vi.fn(); const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById}).execute({lines: [{productId: "p1", palletCount: 1}, {productId: "p1", palletCount: 2}]}, "en"); expect(result).toMatchObject({status: "invalid_plan", reason: "duplicate_product"}); expect(findById).not.toHaveBeenCalled(); });
  it.each(["not a valid id", " product-1", "product-1 ", "product\u0000-1", "a".repeat(65)])("rejects malformed customer Product ID %j before catalog access", async (productId) => { const findById = vi.fn().mockRejectedValue(new Error("must not run")); const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById}).execute({lines: [{productId, palletCount: 1}]}, "en"); expect(result).toEqual({status: "invalid_plan", reason: "invalid_product_id"}); expect(findById).not.toHaveBeenCalled(); });
  it("calls the catalog exactly once for one valid line", async () => { const findById = vi.fn().mockResolvedValue({status: "found", product}); await new CalculateExportLoadPlan({listPublished: vi.fn(), findById}).execute({lines: [{productId: "p1", palletCount: 1}]}, "en"); expect(findById).toHaveBeenCalledTimes(1); });
  it.each([["draft", "product_unpublished"], ["archived", "product_unpublished"]] as const)("classifies %s Products", async (status, expected) => { const result = await calculateWith({...product, status}); expect(result).toMatchObject({status: expected}); });
  it("classifies locale mismatch", async () => expect(calculateWith({...product, locale: "tr"})).resolves.toMatchObject({status: "product_locale_unavailable"}));
  it("preserves an explicit locale-unavailable lookup", async () => { const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById: vi.fn().mockResolvedValue({status: "locale_unavailable"})}).execute({lines: [{productId: "p1", palletCount: 1}]}, "en"); expect(result).toMatchObject({status: "product_locale_unavailable"}); });
  it("does not classify an internal invalid Product identifier as missing", async () => { const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById: vi.fn().mockResolvedValue({status: "malformed_catalog_data"})}).execute({lines: [{productId: "p1", palletCount: 1}]}, "en"); expect(result).toEqual({status: "malformed_catalog_data", productId: "p1"}); });
  it("rejects Product substitution", async () => expect(calculateWith({...product, id: "p2"})).resolves.toMatchObject({status: "malformed_catalog_data"}));
  it.each([{...product, status: "unknown"}, {...product, locale: "xx"}, {...product, name: "Bad\u0000name"}, {...product, packaging: {...packaging, unitsPerPallet: 99}}, "bad"])("rejects malformed catalog data", async (value) => expect(calculateWith(value)).resolves.toMatchObject({status: "malformed_catalog_data"}));
  it("classifies catalog exceptions", async () => { const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById: vi.fn().mockRejectedValue(new Error("provider"))}).execute({lines: [{productId: "p1", palletCount: 1}]}, "en"); expect(result).toEqual({status: "catalog_failure"}); });
  it("returns typed listing failures", async () => { await expect(new ListEligibleLogisticsProducts({listPublished: vi.fn().mockRejectedValue(new Error("provider")), findById: vi.fn()}).execute("en")).resolves.toEqual({status: "catalog_failure"}); await expect(new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue("bad"), findById: vi.fn()}).execute("en")).resolves.toEqual({status: "malformed_catalog_data"}); });
  it("rejects duplicate listing IDs deterministically", async () => expect(new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue([product, product]), findById: vi.fn()}).execute("en")).resolves.toEqual({status: "malformed_catalog_data"}));
  it.each([{...product, status: "draft"}, {...product, status: "archived"}, {...product, locale: "tr"}, {...product, status: "unknown"}, {...product, locale: "xx"}, {...product, id: "bad id"}, {...product, name: "bad\u0000name"}, {...product, packaging: {...packaging, unitsPerPallet: 99}}])("fails closed for invalid listing values", async (value) => expect(new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue([value]), findById: vi.fn()}).execute("en")).resolves.toEqual({status: "malformed_catalog_data"}));
  it("returns a deeply frozen ready listing without mutating catalog data", async () => { const source = structuredClone(product); const useCase = new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue([source]), findById: vi.fn()}); const result = await useCase.execute("en"); expect(result.status).toBe("ready"); if (result.status !== "ready") return; expect(Object.isFrozen(result)).toBe(true); expect(Object.isFrozen(result.eligible)).toBe(true); expect(Object.isFrozen(result.eligible[0])).toBe(true); expect(Object.isFrozen(result.eligible[0].packaging)).toBe(true); try { (result.eligible[0] as {name: string}).name = "Changed"; } catch {} try { (result.eligible[0].packaging as {unitsPerPackage: number}).unitsPerPackage = 999; } catch {} expect(result.eligible[0]).toMatchObject({name: "Bottle", packaging: {unitsPerPackage: 10}}); expect(source).toEqual(product); const repeated = await useCase.execute("en"); expect(repeated).toMatchObject({status: "ready", eligible: [{name: "Bottle", packaging: {unitsPerPackage: 10}}]}); });
  it("accepts an empty valid catalog", async () => expect(new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue([]), findById: vi.fn()}).execute("en")).resolves.toEqual({status: "ready", eligible: [], unavailable: []}));
  it("deep-freezes unavailable Product DTOs", async () => { const result = await new ListEligibleLogisticsProducts({listPublished: vi.fn().mockResolvedValue([{...product, packaging: undefined}]), findById: vi.fn()}).execute("en"); expect(result.status).toBe("ready"); if (result.status === "ready") expect(Object.isFrozen(result.unavailable[0])).toBe(true); });
  it("returns insufficient data for a mixed eligible and missing-profile plan", async () => { const products = new Map<string, unknown>([["p1", product], ["p2", {...product, id: "p2", sku: "SKU-2", packaging: undefined}]]); const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById: vi.fn(async (id: string) => ({status: "found", product: products.get(id)}))}).execute({lines: [{productId: "p1", palletCount: 1}, {productId: "p2", palletCount: 1}]}, "en"); expect(result).toEqual({status: "insufficient_data", productIds: ["p2"]}); });
  it("correlates each requested ID when resolving multiple Products", async () => { const products = new Map([["p1", product], ["p2", {...product, id: "p2", sku: "SKU-2", packaging: {...packaging, palletGrossWeightKg: 200}}]]); const findById = vi.fn(async (id: string) => ({status: "found", product: products.get(id)})); const result = await new CalculateExportLoadPlan({listPublished: vi.fn(), findById}).execute({lines: [{productId: "p2", palletCount: 1}, {productId: "p1", palletCount: 1}]}, "en"); expect(findById.mock.calls.map(([id]) => id)).toEqual(["p2", "p1"]); expect(result).toMatchObject({status: "calculated", lines: [{packaging: {productId: "p2", grossPalletWeightGrams: 200_000}}, {packaging: {productId: "p1", grossPalletWeightGrams: 100_000}}]}); });
});

async function calculateWith(value: unknown) { return new CalculateExportLoadPlan({listPublished: vi.fn(), findById: vi.fn().mockResolvedValue({status: "found", product: value})}).execute({lines: [{productId: "p1", palletCount: 1}]}, "en"); }
