import {renderToStaticMarkup} from "react-dom/server";
import {readFileSync} from "node:fs";
import {describe, expect, it} from "vitest";
import {listInquiryProductOptions} from "@/composition/inquiries/inquiry-presentation";
import {AllProductsAdded, FieldError, InquiryForm, InquiryProductEmptyState, InquiryProductLineFields, InquirySubmissionFeedback, inquiryInvalidProps, ProductAddControls, RemoveProductButton} from "@/features/inquiries/presentation/components/inquiry-form";
import {mapInquiryDraft, parseInquiryQuantity, preselectInquiryProduct, preselectInquiryProducts} from "@/features/inquiries/presentation/parsers/inquiry-draft-mapper";
import {createInquiryMetadata} from "@/features/inquiries/presentation/seo/inquiry-metadata";
import {createInitialInquiryFormState, inquiryFormReducer} from "@/features/inquiries/presentation/state/inquiry-form-reducer";
import arMessages from "@/i18n/messages/ar.json";
import enMessages from "@/i18n/messages/en.json";
import faMessages from "@/i18n/messages/fa.json";
import trMessages from "@/i18n/messages/tr.json";

const labels = {customer:"Contact",fullName:"Name",company:"Company",country:"Country",city:"City",email:"Email",phone:"Phone",preferredContact:"Preferred",contactMethods:{email:"Email",whatsapp:"WhatsApp",telegram:"Telegram",phone:"Phone"},products:"Products",product:"Product",requestedQuantityRequired:"Requested quantity (required)",unitRequired:"Unit (required)",selectUnit:"Select unit",units:{pieces:"Pieces",packages:"Packages",pallets:"Pallets",truckloads:"Truckloads"},removeProduct:"Remove",productSelection:{emptyTitle:"No products added yet",emptyDescription:"Select products",selectProduct:"Select product",productPlaceholder:"Choose a product",addProduct:"Add product",addAnotherProduct:"Add another product",allProductsAdded:"All available products have been added."},errors:{invalidField:"Invalid",quantityRequired:"Quantity required",quantityInvalid:"Invalid quantity",quantityTooLarge:"Too large",unitRequired:"Unit required",productsRequired:"Product required",privacyRequired:"Consent required",destinationDependency:"Country required"},destination:"Destination",destinationCountry:"Country",destinationCity:"City",message:"Message",privacyPrefix:"Consent",privacyLink:"Privacy Policy",privacySuffix:"Read it first.",submit:"Submit",submitting:"Submitting",succeeded:"Succeeded",reference:"Inquiry reference",productUnavailable:"Product unavailable. Retry.",serviceFailure:"Service unavailable",retry:"Details preserved. Retry.",rateLimited:"Rate limited",timeout:"Timed out",invalid:"Invalid"} as const;
const fields = {fullName:"Buyer Name",company:"",country:"Türkiye",city:"",email:"buyer@example.com",phone:"+90 555 123 4567",preferredMethod:"email",destinationCountry:"",destinationCity:"",message:"",privacyAccepted:true} as const;
const line = {productId:"ylp-gb-250-og-rd",quantityText:"25",unit:"pallets" as const};

describe("Inquiry presentation", () => {
  it("offers exactly nine localized published Products", async () => { const en = await listInquiryProductOptions("en"); const fa = await listInquiryProductOptions("fa"); expect(en).toHaveLength(9); expect(fa).toHaveLength(9); expect(en[0].name).not.toBe(fa[0].name); });
  it.each([["1",1],["1000000000",1_000_000_000],["",null],[" ",null],["0",null],["-1",null],["+1",null],["01",null],["1.5",null],["1e2",null],["9007199254740992",null],["1000000001",null],["12x",null],["1\u0000",null]] as const)("strictly parses requested quantity %s", (raw, expected) => expect(parseInquiryQuantity(raw)).toBe(expected));
  it.each(["pieces","packages","pallets","truckloads"] as const)("maps valid requested %s", (unit) => { const result = mapInquiryDraft(fields, [{...line,unit}], "en"); expect(result.status).toBe("valid"); if(result.status === "valid") expect(result.input.items).toEqual([{productId:line.productId,quantity:25,unit}]); });
  it("maps multiple independent quantities and no trusted Product facts", () => { const result = mapInquiryDraft(fields, [line,{productId:"ylp-gb-250-cl-rd",quantityText:"12",unit:"packages"}], "en"); expect(result.status).toBe("valid"); if(result.status === "valid") expect(result.input.items).toEqual([{productId:line.productId,quantity:25,unit:"pallets"},{productId:"ylp-gb-250-cl-rd",quantity:12,unit:"packages"}]); expect(JSON.stringify(result)).not.toMatch(/sku|slug|productName|packaging|price|image/u); });
  it.each([[{...line,quantityText:""},"quantity","required"],[{...line,unit:"" as const},"unit","required"],[{...line,unit:"boxes" as never},"unit","invalid"]] as const)("returns typed line failure", (invalidLine, field, code) => expect(mapInquiryDraft(fields,[invalidLine],"en")).toMatchObject({status:"invalid",failure:{field,code,itemIndex:0,productId:line.productId}}));
  it("validates every Product row", () => expect(mapInquiryDraft(fields,[line,{productId:"ylp-gb-250-cl-rd",quantityText:"",unit:"pieces"}],"en")).toMatchObject({status:"invalid",failure:{field:"quantity",itemIndex:1,productId:"ylp-gb-250-cl-rd"}}));
  it.each([
    [{fullName:"x"},"fullName"],[{fullName:"x".repeat(121)},"fullName"],[{company:"x"},"company"],[{company:"x".repeat(161)},"company"],[{country:"x"},"country"],[{country:"x".repeat(101)},"country"],[{city:"x"},"city"],[{city:"x".repeat(101)},"city"],[{email:""},"email"],[{phone:"123"},"phone"],[{preferredMethod:"unsupported"},"preferredContact"],[{destinationCountry:"",destinationCity:"Paris"},"destinationCountry"],[{destinationCountry:"x"},"destinationCountry"],[{destinationCity:"x",destinationCountry:"France"},"destinationCity"],[{message:"x".repeat(2001)},"message"],[{privacyAccepted:false},"privacy"],
  ] as const)("aligns invalid domain boundary with %s", (change, expected) => expect(mapInquiryDraft({...fields,...change},[line],"en")).toMatchObject({status:"invalid",failure:{field:expected}}));
  it.each([
    {fullName:"ab"},{fullName:"x".repeat(120)},{company:"ab"},{company:"x".repeat(160)},{country:"ab"},{country:"x".repeat(100)},{city:"ab"},{city:"x".repeat(100)},{email:`${"a".repeat(250)}@a.b`},{phone:"1     2"},{phone:`+1${" ".repeat(37)}2`},{destinationCountry:"ab"},{destinationCountry:"x".repeat(100)},{destinationCountry:"France",destinationCity:"ab"},{destinationCountry:"France",destinationCity:"x".repeat(100)},{message:"x"},{message:"x".repeat(2000)},
  ])("accepts an exact domain boundary", (change) => expect(mapInquiryDraft({...fields,...change},[line],"en").status).toBe("valid"));
  it.each(["\u0000","\n","\r","\t","\u007f","\u0085","\u2028","\u2029"])("rejects prohibited single-line control %s", (control) => { for (const field of ["fullName","company","country","city","email","phone","destinationCountry","destinationCity"] as const) expect(mapInquiryDraft({...fields,[field]:`Valid${control}value`},[line],"en").status).toBe("invalid"); });
  it("normalizes permitted message newlines and rejects prohibited controls", () => { const valid = mapInquiryDraft({...fields,message:"Line 1\r\nLine 2"},[line],"en"); expect(valid.status).toBe("valid"); if(valid.status === "valid") expect(valid.input.message).toBe("Line 1\nLine 2"); expect(mapInquiryDraft({...fields,message:"Bad\u0000message"},[line],"en")).toMatchObject({status:"invalid",failure:{field:"message"}}); });
  it("requires both authoritative contact values regardless of preference", () => { for (const preferredMethod of ["email","whatsapp","phone"] as const) { expect(mapInquiryDraft({...fields,preferredMethod,email:""},[line],"en").status).toBe("invalid"); expect(mapInquiryDraft({...fields,preferredMethod,phone:""},[line],"en").status).toBe("invalid"); } });
  it("preselects only one unambiguous available canonical Product with a fresh empty request", async () => { const products = await listInquiryProductOptions("en"); const expected = [{productId:products[0].id,quantityText:"",unit:""}]; expect(preselectInquiryProduct(products,products[0].id)).toEqual(expected); expect(preselectInquiryProduct(products,"invalid")).toEqual([]); expect(preselectInquiryProducts(products,[])).toEqual([]); expect(preselectInquiryProducts(products,[products[0].id,products[0].id])).toEqual([]); expect(preselectInquiryProducts(products,[products[0].id,products[1].id])).toEqual([]); expect(preselectInquiryProducts(products,[" "])).toEqual([]); expect(preselectInquiryProducts(products,Array(20).fill(products[0].id))).toEqual([]); });
  it("re-adding a Product starts from fresh empty quantity and unit", async () => { const products = await listInquiryProductOptions("en"); expect(preselectInquiryProduct(products,products[0].id)).toEqual(preselectInquiryProduct(products,products[0].id)); });
  it("provides line-specific accessible error bindings", () => { const failure = {field:"quantity",code:"required",itemIndex:1,productId:"p2"} as const; expect(inquiryInvalidProps(failure,"quantity",1)).toEqual({"aria-invalid":true,"aria-describedby":"inquiry-quantity-1-error"}); expect(inquiryInvalidProps(failure,"quantity",0)).toEqual({}); expect(renderToStaticMarkup(<FieldError id="inquiry-quantity-1-error">Quantity required</FieldError>)).toContain('id="inquiry-quantity-1-error"'); expect(inquiryInvalidProps({field:"privacy",code:"required"},"privacy")).toEqual({"aria-invalid":true,"aria-describedby":"inquiry-privacy-error"}); });
  it("renders a neutral semantic Product empty state with a decorative icon", () => { const html = renderToStaticMarkup(<InquiryProductEmptyState title="No products added yet" description="Select products"><button type="button">Add product</button></InquiryProductEmptyState>); expect(html).toContain("No products added yet"); expect(html).toContain("Select products"); expect(html).toContain('aria-hidden="true"'); expect(html).toContain('focusable="false"'); expect(html).toContain("Add product"); expect(html).not.toMatch(/aria-invalid|text-red/u); });
  it("renders no fabricated Product row, quantity, or unit initially", async () => { const html = renderToStaticMarkup(<InquiryForm locale="en" products={await listInquiryProductOptions("en")} labels={labels} privacyHref="/en/privacy" />); expect(html).toContain("No products added yet"); expect(html).toContain('value="" selected=""'); expect(html).not.toContain("Requested quantity"); expect(html).not.toContain("Select unit"); expect(html).not.toContain("YLP-GB-"); });
  it("adds only an explicitly selected available Product with fresh request fields", () => { let state = createInitialInquiryFormState(true); expect(inquiryFormReducer(state,{type:"add_product",availableIds:[line.productId]}).lines).toEqual([]); state=inquiryFormReducer(state,{type:"select_pending_product",productId:line.productId}); expect(state.lines).toEqual([]); expect(inquiryFormReducer(state,{type:"add_product",availableIds:[line.productId]}).lines).toEqual([{productId:line.productId,quantityText:"",unit:""}]); });
  it("renders native and visible required quantity/unit semantics", () => { const html=renderToStaticMarkup(<InquiryProductLineFields line={{productId:line.productId,quantityText:"",unit:""}} index={0} labels={labels} fieldClass="field" onQuantityChange={()=>{}} onUnitChange={()=>{}} />); expect(html).toContain("Requested quantity (required)"); expect(html).toContain("Unit (required)"); expect((html.match(/required=""/gu)??[])).toHaveLength(2); expect(html).toContain('<option value="" selected="">Select unit</option>'); });
  it("renders an accessible emerald success panel with the real reference", () => { const html=renderToStaticMarkup(<InquirySubmissionFeedback labels={labels} state={{feedback:"succeeded",inquiryId:"server-reference-123",failure:null,submissionFailure:null}} />); expect(html).toContain('role="status"'); expect(html).toContain('aria-live="polite"'); expect(html).toContain("bg-emerald-50"); expect(html).toContain("Succeeded"); expect(html).toContain("Inquiry reference"); expect(html).toContain("server-reference-123"); });
  it.each([{failure:null,submissionFailure:"service" as const,message:"Service unavailable"},{failure:null,submissionFailure:"timeout" as const,message:"Timed out"},{failure:null,submissionFailure:"rate_limited" as const,message:"Rate limited"},{failure:{field:"products",code:"invalid"} as const,submissionFailure:"service" as const,message:"Product unavailable"}])("renders accessible preserved-data failure feedback: $message", ({failure,submissionFailure,message}) => { const html=renderToStaticMarkup(<InquirySubmissionFeedback labels={labels} state={{feedback:"failed",inquiryId:null,failure,submissionFailure}} />); expect(html).toContain('role="alert"'); expect(html).toContain("bg-red-50"); expect(html).toContain(message); expect(html).toContain("Retry"); });
  it("renders required semantics for every Product row", () => { const html=renderToStaticMarkup(<><InquiryProductLineFields line={{productId:"product-1",quantityText:"",unit:""}} index={0} labels={labels} fieldClass="field" onQuantityChange={()=>{}} onUnitChange={()=>{}} /><InquiryProductLineFields line={{productId:"product-2",quantityText:"",unit:""}} index={1} labels={labels} fieldClass="field" onQuantityChange={()=>{}} onUnitChange={()=>{}} /></>); expect((html.match(/required=""/gu)??[])).toHaveLength(4); expect(html).toContain('id="inquiry-quantity-0"'); expect(html).toContain('id="inquiry-unit-1"'); });
  it("renders an accessible all-products-selected message", () => { const html=renderToStaticMarkup(<AllProductsAdded message={labels.productSelection.allProductsAdded} />); expect(html).toContain('role="status"'); expect(html).toContain("All available products have been added."); });
  it("uses explicit safe button types for Product addition and removal", () => { const add=renderToStaticMarkup(<ProductAddControls products={[{id:line.productId,sku:"SKU",name:"Bottle"}]} value={line.productId} onChange={()=>{}} onAdd={()=>{}} fieldClass="field" label="Product" placeholder="Choose" action="Add product" error={null} invalidProps={{}} />); const remove=renderToStaticMarkup(<RemoveProductButton label="Remove: Bottle" onRemove={()=>{}} />); expect(add).toContain('<button type="button"'); expect(remove).toContain('<button type="button"'); expect(remove).toContain('aria-label="Remove: Bottle"'); });
  it("keeps Product-required validation neutral until review and accessible afterward", () => { expect(inquiryInvalidProps(null,"products")).toEqual({}); const result = mapInquiryDraft(fields,[],"en"); expect(result).toMatchObject({status:"invalid",failure:{field:"products",code:"required"}}); if(result.status === "invalid") expect(inquiryInvalidProps(result.failure,"products")).toEqual({"aria-invalid":true,"aria-describedby":"inquiry-products-error"}); });
  it("keeps matching Product-selection locale keys", () => { const messages = [enMessages,trMessages,faMessages,arMessages].map(({InquiryProductSelection}) => InquiryProductSelection); const keys = Object.keys(messages[0]).sort(); for(const message of messages) expect(Object.keys(message).sort()).toEqual(keys); });
  it("keeps locale catalogs on the active-locale Server Component boundary", () => { const client=readFileSync("src/features/inquiries/presentation/components/inquiry-form.tsx","utf8"); const route=readFileSync("src/app/[locale]/inquiry/page.tsx","utf8"); expect(client).not.toMatch(/i18n\/messages|\.json["']/u); expect(route).toContain("getTranslations"); expect(route).toContain('namespace: "InquiryFormCorrections"'); expect(route).toContain('namespace: "InquiryProductSelection"'); });
  it("renders the active submit contract without leaking customer data to URLs or storage", async () => { const html = renderToStaticMarkup(<InquiryForm locale="en" products={await listInquiryProductOptions("en")} labels={labels} privacyHref="/en/privacy" />); expect(html).toContain('href="/en/privacy"'); expect(html).toContain('type="checkbox"'); expect(html).not.toContain('checked=""'); expect(html).toContain('<form'); expect(html).toContain('type="submit"'); expect(html).not.toContain("action="); expect(html).not.toMatch(/localStorage|sessionStorage|inquiryId/u); });
  it("uses a clean canonical with all alternates", () => { const metadata = createInquiryMetadata("fa"); expect(metadata.alternates?.canonical).toBe("https://yolpol.com/fa/inquiry"); expect(metadata.alternates?.languages).toMatchObject({en:"https://yolpol.com/en/inquiry",tr:"https://yolpol.com/tr/inquiry",fa:"https://yolpol.com/fa/inquiry",ar:"https://yolpol.com/ar/inquiry","x-default":"https://yolpol.com/en/inquiry"}); });
});
