import {describe, expect, it} from "vitest";
import {InquiryPresenter} from "@/features/inquiries/presentation/presenters/inquiry-presenter";

describe("InquiryPresenter", () => {
  const presenter = new InquiryPresenter(); const inquiry = {inquiryId: "safe-id", status: "received" as const, createdAt: "2026-01-01T00:00:00.000Z"};
  it("maps accepted and partial-notification outcomes", () => { const conversationAccessToken = `ypc_${"A".repeat(43)}`; expect(presenter.present({status: "accepted", inquiry, conversationAccessToken})).toEqual({state: "accepted", inquiryId: "safe-id", createdAt: inquiry.createdAt}); expect(presenter.present({status: "accepted_with_notification_failures", inquiry, conversationAccessToken, failedChannels: ["email"]})).toEqual({state: "accepted_with_notification_warning", inquiryId: "safe-id", createdAt: inquiry.createdAt, failedChannels: ["email"]}); });
  it.each([["contact.fullName", "fullName"], ["contact.company", "company"], ["contact.email", "email"], ["contact.phone", "phone"], ["contact.telegramUsername", "telegramUsername"], ["contact.preferredMethod", "preferredContactMethod"], ["location.country", "country"], ["location.city", "city"], ["destination.country", "destination"], ["message", "message"], ["items", "products"], ["items.productId", "products"], ["items.0.quantity", "quantity"], ["items.0.unit", "unit"], ["privacy.accepted", "privacy"], ["source.path", "form"], ["unknown.internal", "form"]] as const)("maps validation path %s to %s", (field, expected) => expect(presenter.present({status: "validation_failed", field})).toEqual({state: "validation_error", field: expected}));
  it("maps Product failures without internal data", () => { for (const result of [{status: "product_not_found", productId: "secret-product"}, {status: "product_unavailable", productId: "secret-product"}, {status: "locale_not_available", productId: "secret-product"}] as const) expect(presenter.present(result)).toEqual({state: "product_error"}); });
  it("maps persistence failures to integration unavailable without provider leakage", () => { expect(presenter.present({status: "persistence_failed"})).toEqual({state: "integration_unavailable"}); expect(presenter.present({status: "duplicate_inquiry"})).toEqual({state: "integration_unavailable"}); });
  it("maps dependency failures without exposing dependency details", () => { expect(presenter.present({status: "dependency_failed", dependency: "catalog"})).toEqual({state: "integration_unavailable"}); });
});
