import {beforeEach, describe, expect, it, vi} from "vitest";
import {SubmitInquiry} from "@/features/inquiries/application/use-cases/submit-inquiry";
import {DuplicateInquiryIdError} from "@/features/inquiries/application/ports/inquiry-ports";
import {FakeClock, FakeInquiryIdGenerator, FakeInquiryNotificationDispatcher, FakeInquiryProductCatalog, FakeInquiryRepository} from "@/features/inquiries/testing/fakes/inquiry-fakes";
import {testCatalogProduct} from "@/features/inquiries/testing/fixtures/inquiry-fixtures";
import {InquiryTestBuilder} from "@/features/inquiries/testing/builders/inquiry-test-builder";
import {Inquiry} from "@/features/inquiries/domain/entities/inquiry";

const input = {contact: {fullName: "Customer Name", email: "customer@example.test", phone: "+1 202 555 0100", preferredMethod: "email" as const}, location: {country: "United States"}, privacy: {accepted: true, policyVersion: "test-policy-v1"}, source: {locale: "en" as const, path: "/en/products"}, items: [{productId: "test-product-1", quantity: 12, unit: "pieces" as const}]};
describe("SubmitInquiry", () => {
  let operations: string[], repository: FakeInquiryRepository, catalog: FakeInquiryProductCatalog, notifications: FakeInquiryNotificationDispatcher, clock: FakeClock, idGenerator: FakeInquiryIdGenerator;
  beforeEach(() => { operations = []; repository = new FakeInquiryRepository(operations); catalog = new FakeInquiryProductCatalog([testCatalogProduct]); notifications = new FakeInquiryNotificationDispatcher(operations); clock = new FakeClock(); idGenerator = new FakeInquiryIdGenerator(); });
  const create = () => new SubmitInquiry(repository, catalog, idGenerator, clock, notifications);
  it("uses trusted catalog snapshots, one generated ID, and one application-owned consent time", async () => { const result = await create().execute({...input, items: [{...input.items[0], productId: "test-product-1", quantity: 22}]}); expect(result).toEqual({status: "accepted", inquiry: {inquiryId: "test-inquiry-generated", status: "received", createdAt: "2026-02-01T00:00:00.000Z"}}); expect(repository.saved[0].items[0]).toMatchObject({sku: "TEST-SKU-1", slug: "test-bottle", productName: "Test Bottle", quantity: 22}); expect(repository.saved[0].privacy.acceptedAt).toEqual(repository.saved[0].createdAt); expect(clock.calls).toBe(1); expect(idGenerator.calls).toBe(1); });
  it("supports multiple Products", async () => { const second = {...testCatalogProduct, id: "test-product-2", sku: "TEST-2", slug: "second"}; catalog = new FakeInquiryProductCatalog([testCatalogProduct, second]); const result = await create().execute({...input, items: [...input.items, {productId: second.id, quantity: 1, unit: "pallets"}]}); expect(result.status).toBe("accepted"); expect(repository.saved[0].items).toHaveLength(2); });
  it.each([[[], "product_not_found"], [[{...testCatalogProduct, status: "draft" as const}], "product_unavailable"], [[{...testCatalogProduct, localizedNames: {tr: "Test"}}], "locale_not_available"]] as const)("returns %s catalog outcome", async (products, status) => { catalog = new FakeInquiryProductCatalog(products); expect((await create().execute(input)).status).toBe(status); });
  it("persists before requesting both channels", async () => { await create().execute(input); expect(operations).toEqual(["persist", "notify:email", "notify:telegram"]); });
  it.each([["email"], ["telegram"]] as const)("attempts both channels when %s fails", async (channel) => { notifications.failures.add(channel); const result = await create().execute(input); expect(result).toMatchObject({status: "accepted_with_notification_failures", failedChannels: [channel]}); expect(notifications.requested).toEqual(["email", "telegram"]); });
  it("reports both notification failures without losing acceptance", async () => { notifications.failures.add("email"); notifications.failures.add("telegram"); expect(await create().execute(input)).toMatchObject({status: "accepted_with_notification_failures", failedChannels: ["email", "telegram"]}); expect(repository.saved).toHaveLength(1); });
  it.each([[new DuplicateInquiryIdError(), "duplicate_inquiry"], [new Error("database secret detail"), "persistence_failed"]] as const)("maps persistence failure to %s", async (error, status) => { repository.failWith = error; const result = await create().execute(input); expect(result).toEqual({status}); expect(notifications.requested).toEqual([]); expect(JSON.stringify(result)).not.toContain("secret"); });
  it("returns safe validation results", async () => { expect(await create().execute({...input, privacy: {...input.privacy, accepted: false}})).toEqual({status: "validation_failed", field: "privacy.accepted"}); });
  it.each([new Error("catalog-provider-secret"), "non-error-secret"])("contains thrown catalog failures", async (failure) => { catalog.failWith = failure; const result = await create().execute(input); expect(result).toEqual({status: "dependency_failed", dependency: "catalog"}); expect(JSON.stringify(result)).not.toContain("secret"); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); });
  it.each([{...testCatalogProduct, id: "wrong-id"}, {...testCatalogProduct, sku: ""}, {...testCatalogProduct, slug: ""}, {...testCatalogProduct, status: "unknown"}, {...testCatalogProduct, localizedNames: null}])("rejects malformed or mismatched catalog output", async (returned) => { catalog.findById = async () => returned as never; expect(await create().execute(input)).toEqual({status: "dependency_failed", dependency: "catalog"}); expect(repository.saved).toHaveLength(0); });
  it("rejects the same returned Product for different requested IDs", async () => { const first = {...testCatalogProduct}; catalog.findById = async () => first; const result = await create().execute({...input, items: [{productId: "test-product-1", quantity: 3, unit: "pieces"}, {productId: "test-product-2", quantity: 4, unit: "pallets"}]}); expect(result).toEqual({status: "dependency_failed", dependency: "catalog"}); expect(repository.saved).toHaveLength(0); });
  it("keeps missing locale distinct from malformed localized content", async () => { catalog.findById = async () => ({...testCatalogProduct, localizedNames: {tr: "Şişe"}}); expect(await create().execute(input)).toEqual({status: "locale_not_available", productId: "test-product-1"}); catalog.findById = async () => ({...testCatalogProduct, localizedNames: {en: 42}} as never); expect(await create().execute(input)).toEqual({status: "dependency_failed", dependency: "catalog"}); });
  it.each(["clock", "id_generator"] as const)("maps %s failure without side effects", async (dependency) => { if (dependency === "clock") clock.failWith = new Error("clock secret"); else idGenerator.failWith = "id secret"; expect(await create().execute(input)).toEqual({status: "dependency_failed", dependency}); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); expect(clock.calls).toBe(1); expect(idGenerator.calls).toBe(dependency === "clock" ? 0 : 1); });
  it.each([new Date(Number.NaN), "not-a-date"])("rejects invalid non-throwing Clock output", async (value) => { clock.now = () => { clock.calls += 1; return value as never; }; expect(await create().execute(input)).toEqual({status: "dependency_failed", dependency: "clock"}); expect(clock.calls).toBe(1); expect(idGenerator.calls).toBe(0); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); });
  it("copies the Clock result before a defective adapter can mutate it", async () => { const returned = new Date("2026-02-01T00:00:00.000Z"); clock.now = () => { clock.calls += 1; return returned; }; expect((await create().execute(input)).status).toBe("accepted"); returned.setTime(Number.NaN); expect(repository.saved[0].createdAt.toISOString()).toBe("2026-02-01T00:00:00.000Z"); expect(repository.saved[0].privacy.acceptedAt.toISOString()).toBe("2026-02-01T00:00:00.000Z"); });
  it.each(["", "   ", "invalid/id", "x".repeat(129), 42])("rejects invalid non-throwing generated ID", async (value) => { idGenerator.generate = () => { idGenerator.calls += 1; return value as never; }; expect(await create().execute(input)).toEqual({status: "dependency_failed", dependency: "id_generator"}); expect(clock.calls).toBe(1); expect(idGenerator.calls).toBe(1); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); });
  it.each([{field: "productId", value: "invalid/id"}, {field: "productId", value: "bad\u0000id"}, {field: "productId", value: `a${"x".repeat(64)}`}, {field: "sku", value: ""}, {field: "sku", value: "BAD\nSKU"}, {field: "sku", value: "S".repeat(65)}, {field: "slug", value: "Invalid Slug"}, {field: "slug", value: "bad\u0000slug"}, {field: "slug", value: `a-${"b".repeat(120)}`}, {field: "productName", value: ""}, {field: "productName", value: "Bad\u0000Name"}, {field: "productName", value: "Bad\nName"}, {field: "productName", value: "Bad\u007fName"}, {field: "productName", value: "Bad\u0085Name"}, {field: "productName", value: "N".repeat(121)}])("maps invalid catalog-owned $field snapshot to dependency failure", async ({field, value}) => { const returned = field === "productName" ? {...testCatalogProduct, localizedNames: {en: value}} : {...testCatalogProduct, [field]: value}; const requested = field === "productId" ? value : input.items[0].productId; catalog.findById = async () => returned as never; const result = await create().execute({...input, items: [{...input.items[0], productId: requested}]}); expect(result).toEqual({status: "dependency_failed", dependency: "catalog"}); if (value) expect(JSON.stringify(result)).not.toContain(value); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); });
  it.each([["en", "English Bottle"], ["tr", "Türk Şişesi"], ["fa", "بطری فارسی"], ["ar", "زجاجة عربية"]] as const)("accepts valid %s localized catalog names", async (locale, name) => { catalog.findById = async () => ({...testCatalogProduct, localizedNames: {[locale]: name}}); const result = await create().execute({...input, source: {locale, path: `/${locale}/products`}}); expect(result.status).toBe("accepted"); expect(repository.saved[0].items[0].productName).toBe(name); });
  it("keeps invalid customer quantity and unit as validation failures", async () => { expect(await create().execute({...input, items: [{...input.items[0], quantity: 0}]})).toEqual({status: "validation_failed", field: "items.quantity"}); expect(await create().execute({...input, items: [{...input.items[0], unit: "boxes" as never}]})).toEqual({status: "validation_failed", field: "items.unit"}); });
  it.each([null, undefined, {}, {status: undefined}, {status: "queued"}, {status: 1}, [], "requested"])("fails closed for malformed email notification result", async (result) => { notifications.dispatch = async (_inquiry, channel) => { notifications.requested.push(channel); return (channel === "email" ? result : {status: "requested"}) as never; }; expect(await create().execute(input)).toMatchObject({status: "accepted_with_notification_failures", failedChannels: ["email"]}); expect(notifications.requested).toEqual(["email", "telegram"]); });
  it.each([null, undefined, {}, {status: undefined}, {status: "queued"}, {status: 1}, [], "requested"])("fails closed for malformed telegram notification result", async (result) => { notifications.dispatch = async (_inquiry, channel) => { notifications.requested.push(channel); return (channel === "telegram" ? result : {status: "requested"}) as never; }; expect(await create().execute(input)).toMatchObject({status: "accepted_with_notification_failures", failedChannels: ["telegram"]}); expect(notifications.requested).toEqual(["email", "telegram"]); });
  it("reports both channels when both notification results are malformed", async () => { notifications.dispatch = async (_inquiry, channel) => { notifications.requested.push(channel); return null as never; }; expect(await create().execute(input)).toMatchObject({status: "accepted_with_notification_failures", failedChannels: ["email", "telegram"]}); });
  it("fails closed for a custom-prototype notification result", async () => { const custom = Object.assign(Object.create({}), {status: "requested"}); notifications.dispatch = async (_inquiry, channel) => { notifications.requested.push(channel); return (channel === "email" ? custom : {status: "requested"}) as never; }; expect(await create().execute(input)).toMatchObject({status: "accepted_with_notification_failures", failedChannels: ["email"]}); expect(notifications.requested).toEqual(["email", "telegram"]); });
  it("does not misclassify unexpected aggregate errors as validation", async () => { vi.spyOn(Inquiry, "create").mockImplementationOnce(() => { throw new TypeError("programmer defect"); }); await expect(create().execute(input)).rejects.toThrow("programmer defect"); expect(repository.saved).toHaveLength(0); expect(notifications.requested).toEqual([]); });
});

describe("FakeInquiryRepository isolation", () => {
  it("isolates saved and returned aggregates", async () => { const repository = new FakeInquiryRepository(); const original = new InquiryTestBuilder().buildNew(); await repository.save(original); original.transitionTo("processing", new Date("2026-01-02")); expect((await repository.findById(original.id.value))?.status).toBe("received"); const returned = await repository.findById(original.id.value); returned?.transitionTo("spam", new Date("2026-01-02")); expect((await repository.findById(original.id.value))?.status).toBe("received"); });
});
