import {beforeEach,describe,expect,it} from "vitest";
import {SubmitInquiry} from "@/features/inquiries/application/use-cases/submit-inquiry";
import {DuplicateInquiryIdError} from "@/features/inquiries/application/ports/inquiry-ports";
import {FakeClock,FakeInquiryIdGenerator,FakeInquiryNotificationDispatcher,FakeInquiryProductCatalog,FakeInquiryRepository} from "@/features/inquiries/testing/fakes/inquiry-fakes";
import {testCatalogProduct} from "@/features/inquiries/testing/fixtures/inquiry-fixtures";

const input={contact:{fullName:"Customer Name",email:"customer@example.test",phone:"+12025550100",preferredMethods:["email"] as const},location:{country:"TR"},privacy:{accepted:true,policyVersion:"test-policy-v2"},source:{locale:"en" as const,path:"/en/inquiry"},items:[{productId:"test-product-1",palletCount:12}]};

describe("SubmitInquiry",()=>{
  let operations:string[],repository:FakeInquiryRepository,catalog:FakeInquiryProductCatalog,notifications:FakeInquiryNotificationDispatcher,clock:FakeClock,idGenerator:FakeInquiryIdGenerator;
  beforeEach(()=>{operations=[];repository=new FakeInquiryRepository(operations);catalog=new FakeInquiryProductCatalog([testCatalogProduct]);notifications=new FakeInquiryNotificationDispatcher(operations);clock=new FakeClock();idGenerator=new FakeInquiryIdGenerator();});
  const create=()=>new SubmitInquiry(repository,catalog,idGenerator,clock,notifications);
  it("persists trusted pallet snapshots before notifications",async()=>{expect((await create().execute(input)).status).toBe("accepted");expect(repository.saved[0].items[0]).toMatchObject({sku:"TEST-SKU-1",quantity:12,unit:"pallets"});expect(operations).toEqual(["persist","notify:email","notify:telegram"]);});
  it("persists canonical main and WhatsApp phones when plus signs are omitted",async()=>{const result=await create().execute({...input,contact:{...input.contact,phone:"989121234567",whatsappPhone:"905321234567",telegramUsername:"@buyer_name",preferredMethods:["email","whatsapp","telegram"]}});expect(result.status).toBe("accepted");expect(repository.saved[0].contact).toMatchObject({phone:"+989121234567",whatsappPhone:"+905321234567",preferredMethods:["email","whatsapp","telegram"]});});
  it.each([1,26,27,50,100] as const)("accepts and persists %s pallets",async palletCount=>{expect((await create().execute({...input,items:[{...input.items[0],palletCount}]})).status).toBe("accepted");expect(repository.saved[0].items[0]).toMatchObject({quantity:palletCount,unit:"pallets"});});
  it("supports multiple products totaling more than one truck capacity",async()=>{const second={...testCatalogProduct,id:"test-product-2",sku:"TEST-2",slug:"second"};catalog=new FakeInquiryProductCatalog([testCatalogProduct,second]);expect((await create().execute({...input,items:[{productId:testCatalogProduct.id,palletCount:26},{productId:second.id,palletCount:26}]})).status).toBe("accepted");expect(repository.saved[0].items.map(({quantity})=>quantity)).toEqual([26,26]);});
  it.each([["IR","IR"],["IR","TR"],["TR","IR"]] as const)("accepts approved country route %s to %s",async(country,destinationCountry)=>expect((await create().execute({...input,location:{country},destination:{country:destinationCountry}})).status).toBe("accepted"));
  it.each([[0,"items.0.palletCount"],[-1,"items.0.palletCount"],[1.5,"items.0.palletCount"],[1_000_000_001,"items.0.palletCount"]] as const)("rejects invalid pallet count %s",async(palletCount,field)=>expect(await create().execute({...input,items:[{...input.items[0],palletCount}]})).toEqual({status:"validation_failed",field}));
  it.each([[[],"product_not_found"],[[{...testCatalogProduct,status:"draft" as const}],"product_unavailable"]] as const)("returns the catalog outcome",async(products,status)=>{catalog=new FakeInquiryProductCatalog(products);expect((await create().execute(input)).status).toBe(status);});
  it("rejects unavailable packaging data",async()=>{catalog.findById=async()=>({...testCatalogProduct,packaging:undefined});expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"catalog"});});
  it("requires consent",async()=>expect(await create().execute({...input,privacy:{...input.privacy,accepted:false}})).toEqual({status:"validation_failed",field:"privacy.accepted"}));
  it.each([[new DuplicateInquiryIdError(),"duplicate_inquiry"],[new Error("secret"),"persistence_failed"]] as const)("maps persistence errors",async(error,status)=>{repository.failWith=error;expect((await create().execute(input)).status).toBe(status);expect(notifications.requested).toEqual([]);});
  it("keeps acceptance when notification delivery fails",async()=>{notifications.failures.add("email");expect(await create().execute(input)).toMatchObject({status:"accepted_with_notification_failures",failedChannels:["email"]});});
  it("fails closed on malformed catalog output",async()=>{catalog.findById=async()=>({...testCatalogProduct,packaging:{unitsPerPallet:0,grossPalletWeightGrams:1}});expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"catalog"});});
  it.each([new Error("catalog secret"),"non-error failure",null,42] as const)("contains catalog exception %j",async(failure)=>{catalog.failWith=failure;expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"catalog"});expect(repository.saved).toHaveLength(0);});
  it.each([
    ["id",""],["id","bad id"],["id","bad/id"],["id","bad\u0000id"],["id","x".repeat(65)],
    ["sku",""],["sku"," "],["sku","BAD\nSKU"],["sku","BAD\u0000SKU"],["sku","S".repeat(65)],
    ["slug",""],["slug","Invalid Slug"],["slug","bad\u0000slug"],["slug","-leading"],["slug","a".repeat(121)],
  ] as const)("rejects malformed catalog %s %j",async(field,value)=>{catalog.findById=async()=>({...testCatalogProduct,[field]:value}) as never;expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"catalog"});expect(repository.saved).toHaveLength(0);});
  it.each(["", " ", "invalid/id", "with space", "x".repeat(129), 42, null, undefined] as const)("rejects generated ID %j",async(value)=>{idGenerator.generate=()=>value as never;expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"id_generator"});expect(repository.saved).toHaveLength(0);});
  it.each([new Date(Number.NaN),"not-a-date",null,undefined,42] as const)("rejects invalid clock output %j",async(value)=>{clock.now=()=>value as never;expect(await create().execute(input)).toEqual({status:"dependency_failed",dependency:"clock"});expect(idGenerator.calls).toBe(0);});
  it.each(["clock","id"] as const)("contains thrown %s failures",async(dependency)=>{if(dependency==="clock")clock.failWith=new Error("clock secret");else idGenerator.failWith=new Error("id secret");expect(await create().execute(input)).toMatchObject({status:"dependency_failed"});expect(repository.saved).toHaveLength(0);});
  it.each([null,undefined,{},[],"requested",{status:"queued"},{status:1},{status:undefined}] as const)("fails closed for malformed email notification result %j",async(result)=>{notifications.dispatch=async(_inquiry,channel)=>{notifications.requested.push(channel);return(channel==="email"?result:{status:"requested"}) as never;};expect(await create().execute(input)).toMatchObject({status:"accepted_with_notification_failures",failedChannels:["email"]});});
  it.each([null,undefined,{},[],"requested",{status:"queued"},{status:1},{status:undefined}] as const)("fails closed for malformed telegram notification result %j",async(result)=>{notifications.dispatch=async(_inquiry,channel)=>{notifications.requested.push(channel);return(channel==="telegram"?result:{status:"requested"}) as never;};expect(await create().execute(input)).toMatchObject({status:"accepted_with_notification_failures",failedChannels:["telegram"]});});
  it.each([["en","English Bottle"],["tr","Türk Şişesi"],["fa","بطری فارسی"],["ar","زجاجة عربية"]] as const)("persists %s localized catalog names",async(locale,name)=>{catalog.findById=async()=>({...testCatalogProduct,localizedNames:{[locale]:name}});expect((await create().execute({...input,source:{locale,path:`/${locale}/inquiry`}})).status).toBe("accepted");expect(repository.saved[0].items[0].productName).toBe(name);});
});
